#index:
#    path: /
#    controller: App\Controller\DefaultController::index

companys:
  path: /api/companies
  controller: App\Controller\CompanyController::getAll
  methods:
    - GET
company:
  path: /api/companies/{id}
  controller: App\Controller\CompanyController::getById
  methods:
    - GET
new_company:
  path: /api/companies
  controller: App\Controller\CompanyController::add
  methods:
    - POST
update_company:
  path: /api/companies/{id}
  controller: App\Controller\CompanyController::update
  methods:
    - PUT
remove_company:
  path: /api/companies/{id}
  controller: App\Controller\CompanyController::remove
  methods:
    - DELETE

assets:
  path: /api/assets
  controller: App\Controller\AssetController::getAll
  methods:
    - GET
asset:
  path: /api/assets/{id}
  controller: App\Controller\AssetController::getById
  methods:
    - GET
new_asset:
  path: /api/assets
  controller: App\Controller\AssetController::add
  methods:
    - POST
update_asset:
  path: /api/assets/{id}
  controller: App\Controller\AssetController::update
  methods:
    - PUT
remove_asset:
  path: /api/assets/{id}
  controller: App\Controller\AssetController::remove
  methods:
    - DELETE

brokers:
  path: /api/brokers
  controller: App\Controller\BrokerController::getAll
  methods:
    - GET
broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::getById
  methods:
    - GET
new_broker:
  path: /api/brokers
  controller: App\Controller\BrokerController::add
  methods:
    - POST
update_broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::update
  methods:
    - PUT
remove_broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::remove
  methods:
    - DELETE

brokerage_notes:
  path: /api/brokerageNotes
  controller: App\Controller\BrokerageNoteController::getAll
  methods:
    - GET
brokerage_note:
  path: /api/brokerageNotes/{id}
  controller: App\Controller\BrokerageNoteController::getById
  methods:
    - GET
new_brokerage_note:
  path: /api/brokerageNotes
  controller: App\Controller\BrokerageNoteController::add
  methods:
    - POST
update_brokerage_note:
  path: /api/brokerageNotes/{id}
  controller: App\Controller\BrokerageNoteController::update
  methods:
    - PUT
remove_brokerage_note:
  path: /api/brokerageNotes/{id}
  controller: App\Controller\BrokerageNoteController::remove
  methods:
    - DELETE
new_operation_at_brokerage_note:
  path: /api/brokerageNotes/{id}/operations
  controller: App\Controller\BrokerageNoteController::addOperation
  methods:
    - POST
update_operation_at_brokerage_note:
  path: /api/brokerageNotes/{id}/operations/{line}
  controller: App\Controller\BrokerageNoteController::updateOperation
  methods:
    - PUT
remove_operation_at_brokerage_note:
  path: /api/brokerageNotes/{id}/operations/{line}
  controller: App\Controller\BrokerageNoteController::removeOperation
  methods:
    - DELETE

positions:
  path: /api/positions
  controller: App\Controller\PositionController::getAll
  methods:
    - GET

index:
  path: /{resource?}
  requirements:
    resource: .+
  controller: App\Controller\IndexController::index
  methods:
    - GET