#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
  path: /
  controller: App\Controller\IndexController::index
  methods:
    - GET

index:
  path: /{vueRouting}
  controller: App\Controller\IndexController::index
  methods:
    - GET

brokers:
  path: /api/brokers
  controller: App\Controller\BrokerController::getAll
  methods:
    - GET
broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::getById
  methods:
    - GET
new_broker:
  path: /api/brokers
  controller: App\Controller\BrokerController::add
  methods:
    - POST
update_broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::update
  methods:
    - PUT
remove_broker:
  path: /api/brokers/{id}
  controller: App\Controller\BrokerController::remove
  methods:
    - DELETE

brokerage_notes:
  path: /api/brokerageNotes
  controller: App\Controller\BrokerageNoteController::getAll
  methods:
    - GET
brokerage_note:
  path: /api/brokerageNotes/{id}
  controller: App\Controller\BrokerageNoteController::getById
  methods:
    - GET
new_brokerage_note:
  path: /api/brokerageNotes
  controller: App\Controller\BrokerageNoteController::add
  methods:
    - POST
update_brokerage_note:
  path: /api/brokerageNotes/{id}
  controller: App\Controller\BrokerageNoteController::update
  methods:
    - PUT