<?php

namespace App\DataFixtures;

use App\Entity\Asset;
use App\Helper\AssetFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AssetsFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $assetFactory = new AssetFactory();
        
        $manager->persist($assetFactory->makeEntity('WDO', Asset::TYPE_FUTURE_CONTRACT, 'Mini Contrato Dólar'));
        $manager->persist($assetFactory->makeEntity('WIN', Asset::TYPE_FUTURE_CONTRACT, 'Mini Contrato de índice'));
        $manager->persist($assetFactory->makeEntity('DOL', Asset::TYPE_FUTURE_CONTRACT, 'Contrato de Dólar'));
        $manager->persist($assetFactory->makeEntity('IND', Asset::TYPE_FUTURE_CONTRACT, 'Contrato de índice'));

        $manager->persist($assetFactory->makeEntity('AALR3', Asset::TYPE_STOCK, 'ALLIAR'));
        $manager->persist($assetFactory->makeEntity('ABCB4', Asset::TYPE_STOCK, 'ABC BRASIL'));
        $manager->persist($assetFactory->makeEntity('ABEV3', Asset::TYPE_STOCK, 'AMBEV S/A'));
        $manager->persist($assetFactory->makeEntity('AERI3', Asset::TYPE_STOCK, 'AERIS'));
        $manager->persist($assetFactory->makeEntity('AFLT3', Asset::TYPE_STOCK, 'AFLUENTE T'));
        $manager->persist($assetFactory->makeEntity('AGRO3', Asset::TYPE_STOCK, 'BRASILAGRO'));
        $manager->persist($assetFactory->makeEntity('AHEB3', Asset::TYPE_STOCK, 'SPTURIS'));
        $manager->persist($assetFactory->makeEntity('AHEB5', Asset::TYPE_STOCK, 'SPTURIS'));
        $manager->persist($assetFactory->makeEntity('AHEB6', Asset::TYPE_STOCK, 'SPTURIS'));
        $manager->persist($assetFactory->makeEntity('ALPA3', Asset::TYPE_STOCK, 'ALPARGATAS'));
        $manager->persist($assetFactory->makeEntity('ALPA4', Asset::TYPE_STOCK, 'ALPARGATAS'));
        $manager->persist($assetFactory->makeEntity('ALPK3', Asset::TYPE_STOCK, 'ESTAPAR'));
        $manager->persist($assetFactory->makeEntity('ALSC3', Asset::TYPE_STOCK, 'ALIANSCE'));
        $manager->persist($assetFactory->makeEntity('ALSO3', Asset::TYPE_STOCK, 'ALIANSCSONAE'));
        $manager->persist($assetFactory->makeEntity('ALUP11', Asset::TYPE_STOCK, 'ALUPAR'));
        $manager->persist($assetFactory->makeEntity('ALUP3', Asset::TYPE_STOCK, 'ALUPAR'));
        $manager->persist($assetFactory->makeEntity('ALUP4', Asset::TYPE_STOCK, 'ALUPAR'));
        $manager->persist($assetFactory->makeEntity('AMAR3', Asset::TYPE_STOCK, 'LOJAS MARISA'));
        $manager->persist($assetFactory->makeEntity('AMBP3', Asset::TYPE_STOCK, 'AMBIPAR'));
        $manager->persist($assetFactory->makeEntity('ANIM3', Asset::TYPE_STOCK, 'ANIMA'));
        $manager->persist($assetFactory->makeEntity('APER3', Asset::TYPE_STOCK, 'ALPER S.A.'));
        $manager->persist($assetFactory->makeEntity('APTI3', Asset::TYPE_STOCK, 'ALIPERTI'));
        $manager->persist($assetFactory->makeEntity('APTI4', Asset::TYPE_STOCK, 'ALIPERTI'));
        $manager->persist($assetFactory->makeEntity('ARZZ3', Asset::TYPE_STOCK, 'AREZZO CO'));
        $manager->persist($assetFactory->makeEntity('ATOM3', Asset::TYPE_STOCK, 'ATOMPAR'));
        $manager->persist($assetFactory->makeEntity('AURA33', Asset::TYPE_STOCK, 'AURA 360'));
        $manager->persist($assetFactory->makeEntity('AVLL3', Asset::TYPE_STOCK, 'ALPHAVILLE'));
        $manager->persist($assetFactory->makeEntity('AZEV3', Asset::TYPE_STOCK, 'AZEVEDO'));
        $manager->persist($assetFactory->makeEntity('AZEV4', Asset::TYPE_STOCK, 'AZEVEDO'));
        $manager->persist($assetFactory->makeEntity('AZUL4', Asset::TYPE_STOCK, 'AZUL'));
        $manager->persist($assetFactory->makeEntity('B3SA3', Asset::TYPE_STOCK, 'B3'));
        $manager->persist($assetFactory->makeEntity('BAHI3', Asset::TYPE_STOCK, 'BAHEMA'));
        $manager->persist($assetFactory->makeEntity('BALM3', Asset::TYPE_STOCK, 'BAUMER'));
        $manager->persist($assetFactory->makeEntity('BALM4', Asset::TYPE_STOCK, 'BAUMER'));
        $manager->persist($assetFactory->makeEntity('BAUH3', Asset::TYPE_STOCK, 'EXCELSIOR'));
        $manager->persist($assetFactory->makeEntity('BAUH4', Asset::TYPE_STOCK, 'EXCELSIOR'));
        $manager->persist($assetFactory->makeEntity('BAZA3', Asset::TYPE_STOCK, 'AMAZONIA'));
        $manager->persist($assetFactory->makeEntity('BBAS3', Asset::TYPE_STOCK, 'BRASIL'));
        $manager->persist($assetFactory->makeEntity('BBDC3', Asset::TYPE_STOCK, 'BRADESCO'));
        $manager->persist($assetFactory->makeEntity('BBDC4', Asset::TYPE_STOCK, 'BRADESCO'));
        $manager->persist($assetFactory->makeEntity('BBML3', Asset::TYPE_STOCK, 'BBMLOGISTICA'));
        $manager->persist($assetFactory->makeEntity('BBRK3', Asset::TYPE_STOCK, 'BR BROKERS'));
        $manager->persist($assetFactory->makeEntity('BBSE3', Asset::TYPE_STOCK, 'BBSEGURIDADE'));
        $manager->persist($assetFactory->makeEntity('BDLL3', Asset::TYPE_STOCK, 'BARDELLA'));
        $manager->persist($assetFactory->makeEntity('BDLL4', Asset::TYPE_STOCK, 'BARDELLA'));
        $manager->persist($assetFactory->makeEntity('BEEF3', Asset::TYPE_STOCK, 'MINERVA'));
        $manager->persist($assetFactory->makeEntity('BEES3', Asset::TYPE_STOCK, 'BANESTES'));
        $manager->persist($assetFactory->makeEntity('BEES4', Asset::TYPE_STOCK, 'BANESTES'));
        $manager->persist($assetFactory->makeEntity('BGIP3', Asset::TYPE_STOCK, 'BANESE'));
        $manager->persist($assetFactory->makeEntity('BGIP4', Asset::TYPE_STOCK, 'BANESE'));
        $manager->persist($assetFactory->makeEntity('BIDI11', Asset::TYPE_STOCK, 'BANCO INTER'));
        $manager->persist($assetFactory->makeEntity('BIDI3', Asset::TYPE_STOCK, 'BANCO INTER'));
        $manager->persist($assetFactory->makeEntity('BIDI4', Asset::TYPE_STOCK, 'BANCO INTER'));
        $manager->persist($assetFactory->makeEntity('BIOM3', Asset::TYPE_STOCK, 'BIOMM'));
        $manager->persist($assetFactory->makeEntity('BKBR3', Asset::TYPE_STOCK, 'BK BRASIL'));
        $manager->persist($assetFactory->makeEntity('BMEB3', Asset::TYPE_STOCK, 'MERC BRASIL'));
        $manager->persist($assetFactory->makeEntity('BMEB4', Asset::TYPE_STOCK, 'MERC BRASIL'));
        $manager->persist($assetFactory->makeEntity('BMGB4', Asset::TYPE_STOCK, 'BANCO BMG'));
        $manager->persist($assetFactory->makeEntity('BMIN3', Asset::TYPE_STOCK, 'MERC INVEST'));
        $manager->persist($assetFactory->makeEntity('BMIN4', Asset::TYPE_STOCK, 'MERC INVEST'));
        $manager->persist($assetFactory->makeEntity('BMKS3', Asset::TYPE_STOCK, 'BIC MONARK'));
        $manager->persist($assetFactory->makeEntity('BNBR3', Asset::TYPE_STOCK, 'NORD BRASIL'));
        $manager->persist($assetFactory->makeEntity('BOAS3', Asset::TYPE_STOCK, 'BOA VISTA'));
        $manager->persist($assetFactory->makeEntity('BOBR3', Asset::TYPE_STOCK, 'BOMBRIL'));
        $manager->persist($assetFactory->makeEntity('BOBR4', Asset::TYPE_STOCK, 'BOMBRIL'));
        $manager->persist($assetFactory->makeEntity('BPAC11', Asset::TYPE_STOCK, 'BTGP BANCO'));
        $manager->persist($assetFactory->makeEntity('BPAC3', Asset::TYPE_STOCK, 'BTGP BANCO'));
        $manager->persist($assetFactory->makeEntity('BPAC5', Asset::TYPE_STOCK, 'BTGP BANCO'));
        $manager->persist($assetFactory->makeEntity('BPAN4', Asset::TYPE_STOCK, 'BANCO PAN'));
        $manager->persist($assetFactory->makeEntity('BPAR3', Asset::TYPE_STOCK, 'BANPARA'));
        $manager->persist($assetFactory->makeEntity('BPHA3', Asset::TYPE_STOCK, 'BR PHARMA'));
        $manager->persist($assetFactory->makeEntity('BRAP3', Asset::TYPE_STOCK, 'BRADESPAR'));
        $manager->persist($assetFactory->makeEntity('BRAP4', Asset::TYPE_STOCK, 'BRADESPAR'));
        $manager->persist($assetFactory->makeEntity('BRDT3', Asset::TYPE_STOCK, 'PETROBRAS BR'));
        $manager->persist($assetFactory->makeEntity('BRFS3', Asset::TYPE_STOCK, 'BRF SA'));
        $manager->persist($assetFactory->makeEntity('BRGE11', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE12', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE3', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE5', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE6', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE7', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRGE8', Asset::TYPE_STOCK, 'ALFA CONSORC'));
        $manager->persist($assetFactory->makeEntity('BRIV3', Asset::TYPE_STOCK, 'ALFA INVEST'));
        $manager->persist($assetFactory->makeEntity('BRIV4', Asset::TYPE_STOCK, 'ALFA INVEST'));
        $manager->persist($assetFactory->makeEntity('BRKM3', Asset::TYPE_STOCK, 'BRASKEM'));
        $manager->persist($assetFactory->makeEntity('BRKM5', Asset::TYPE_STOCK, 'BRASKEM'));
        $manager->persist($assetFactory->makeEntity('BRKM6', Asset::TYPE_STOCK, 'BRASKEM'));
        $manager->persist($assetFactory->makeEntity('BRML3', Asset::TYPE_STOCK, 'BR MALLS PAR'));
        $manager->persist($assetFactory->makeEntity('BRPR3', Asset::TYPE_STOCK, 'BR PROPERT'));
        $manager->persist($assetFactory->makeEntity('BRQB3', Asset::TYPE_STOCK, 'BRQ'));
        $manager->persist($assetFactory->makeEntity('BRSR3', Asset::TYPE_STOCK, 'BANRISUL'));
        $manager->persist($assetFactory->makeEntity('BRSR5', Asset::TYPE_STOCK, 'BANRISUL'));
        $manager->persist($assetFactory->makeEntity('BRSR6', Asset::TYPE_STOCK, 'BANRISUL'));
        $manager->persist($assetFactory->makeEntity('BSEV3', Asset::TYPE_STOCK, 'BIOSEV'));
        $manager->persist($assetFactory->makeEntity('BSLI3', Asset::TYPE_STOCK, 'BRB BANCO'));
        $manager->persist($assetFactory->makeEntity('BSLI4', Asset::TYPE_STOCK, 'BRB BANCO'));
        $manager->persist($assetFactory->makeEntity('BTOW3', Asset::TYPE_STOCK, 'B2W DIGITAL'));
        $manager->persist($assetFactory->makeEntity('BTTL3', Asset::TYPE_STOCK, 'BATTISTELLA'));
        $manager->persist($assetFactory->makeEntity('CALI3', Asset::TYPE_STOCK, 'CONST A LIND'));
        $manager->persist($assetFactory->makeEntity('CALI4', Asset::TYPE_STOCK, 'CONST A LIND'));
        $manager->persist($assetFactory->makeEntity('CAMB3', Asset::TYPE_STOCK, 'CAMBUCI'));
        $manager->persist($assetFactory->makeEntity('CAML3', Asset::TYPE_STOCK, 'CAMIL'));
        $manager->persist($assetFactory->makeEntity('CARD3', Asset::TYPE_STOCK, 'CSU CARDSYST'));
        $manager->persist($assetFactory->makeEntity('CASH3', Asset::TYPE_STOCK, 'MELIUZ'));
        $manager->persist($assetFactory->makeEntity('CASN3', Asset::TYPE_STOCK, 'CASAN'));
        $manager->persist($assetFactory->makeEntity('CASN4', Asset::TYPE_STOCK, 'CASAN'));
        $manager->persist($assetFactory->makeEntity('CATA3', Asset::TYPE_STOCK, 'IND CATAGUAS'));
        $manager->persist($assetFactory->makeEntity('CATA4', Asset::TYPE_STOCK, 'IND CATAGUAS'));
        $manager->persist($assetFactory->makeEntity('CBEE3', Asset::TYPE_STOCK, 'AMPLA ENERG'));
        $manager->persist($assetFactory->makeEntity('CCPR3', Asset::TYPE_STOCK, 'CYRE COM-CCP'));
        $manager->persist($assetFactory->makeEntity('CCRO3', Asset::TYPE_STOCK, 'CCR SA'));
        $manager->persist($assetFactory->makeEntity('CCXC3', Asset::TYPE_STOCK, 'CCX CARVAO'));
        $manager->persist($assetFactory->makeEntity('CEAB3', Asset::TYPE_STOCK, 'CEA MODAS'));
        $manager->persist($assetFactory->makeEntity('CEBR3', Asset::TYPE_STOCK, 'CEB'));
        $manager->persist($assetFactory->makeEntity('CEBR5', Asset::TYPE_STOCK, 'CEB'));
        $manager->persist($assetFactory->makeEntity('CEBR6', Asset::TYPE_STOCK, 'CEB'));
        $manager->persist($assetFactory->makeEntity('CEDO3', Asset::TYPE_STOCK, 'CEDRO'));
        $manager->persist($assetFactory->makeEntity('CEDO4', Asset::TYPE_STOCK, 'CEDRO'));
        $manager->persist($assetFactory->makeEntity('CEEB3', Asset::TYPE_STOCK, 'COELBA'));
        $manager->persist($assetFactory->makeEntity('CEEB5', Asset::TYPE_STOCK, 'COELBA'));
        $manager->persist($assetFactory->makeEntity('CEEB6', Asset::TYPE_STOCK, 'COELBA'));
        $manager->persist($assetFactory->makeEntity('CEED3', Asset::TYPE_STOCK, 'CEEE-D'));
        $manager->persist($assetFactory->makeEntity('CEED4', Asset::TYPE_STOCK, 'CEEE-D'));
        $manager->persist($assetFactory->makeEntity('CEGR3', Asset::TYPE_STOCK, 'CEG'));
        $manager->persist($assetFactory->makeEntity('CEPE3', Asset::TYPE_STOCK, 'CELPE'));
        $manager->persist($assetFactory->makeEntity('CEPE5', Asset::TYPE_STOCK, 'CELPE'));
        $manager->persist($assetFactory->makeEntity('CEPE6', Asset::TYPE_STOCK, 'CELPE'));
        $manager->persist($assetFactory->makeEntity('CESP3', Asset::TYPE_STOCK, 'CESP'));
        $manager->persist($assetFactory->makeEntity('CESP5', Asset::TYPE_STOCK, 'CESP'));
        $manager->persist($assetFactory->makeEntity('CESP6', Asset::TYPE_STOCK, 'CESP'));
        $manager->persist($assetFactory->makeEntity('CGAS3', Asset::TYPE_STOCK, 'COMGAS'));
        $manager->persist($assetFactory->makeEntity('CGAS5', Asset::TYPE_STOCK, 'COMGAS'));
        $manager->persist($assetFactory->makeEntity('CGRA3', Asset::TYPE_STOCK, 'GRAZZIOTIN'));
        $manager->persist($assetFactory->makeEntity('CGRA4', Asset::TYPE_STOCK, 'GRAZZIOTIN'));
        $manager->persist($assetFactory->makeEntity('CIEL3', Asset::TYPE_STOCK, 'CIELO'));
        $manager->persist($assetFactory->makeEntity('CLSC3', Asset::TYPE_STOCK, 'CELESC'));
        $manager->persist($assetFactory->makeEntity('CLSC4', Asset::TYPE_STOCK, 'CELESC'));
        $manager->persist($assetFactory->makeEntity('CMIG3', Asset::TYPE_STOCK, 'CEMIG'));
        $manager->persist($assetFactory->makeEntity('CMIG4', Asset::TYPE_STOCK, 'CEMIG'));
        $manager->persist($assetFactory->makeEntity('CMSA3', Asset::TYPE_STOCK, 'CIMS'));
        $manager->persist($assetFactory->makeEntity('CMSA4', Asset::TYPE_STOCK, 'CIMS'));
        $manager->persist($assetFactory->makeEntity('CNSY3', Asset::TYPE_STOCK, 'CINESYSTEM'));
        $manager->persist($assetFactory->makeEntity('CNTO3', Asset::TYPE_STOCK, 'CENTAURO'));
        $manager->persist($assetFactory->makeEntity('COCE3', Asset::TYPE_STOCK, 'COELCE'));
        $manager->persist($assetFactory->makeEntity('COCE5', Asset::TYPE_STOCK, 'COELCE'));
        $manager->persist($assetFactory->makeEntity('COCE6', Asset::TYPE_STOCK, 'COELCE'));
        $manager->persist($assetFactory->makeEntity('COGN3', Asset::TYPE_STOCK, 'COGNA ON'));
        $manager->persist($assetFactory->makeEntity('CORR3', Asset::TYPE_STOCK, 'COR RIBEIRO'));
        $manager->persist($assetFactory->makeEntity('CORR4', Asset::TYPE_STOCK, 'COR RIBEIRO'));
        $manager->persist($assetFactory->makeEntity('CPFE3', Asset::TYPE_STOCK, 'CPFL ENERGIA'));
        $manager->persist($assetFactory->makeEntity('CPLE3', Asset::TYPE_STOCK, 'COPEL'));
        $manager->persist($assetFactory->makeEntity('CPLE5', Asset::TYPE_STOCK, 'COPEL'));
        $manager->persist($assetFactory->makeEntity('CPLE6', Asset::TYPE_STOCK, 'COPEL'));
        $manager->persist($assetFactory->makeEntity('CRDE3', Asset::TYPE_STOCK, 'CR2'));
        $manager->persist($assetFactory->makeEntity('CRFB3', Asset::TYPE_STOCK, 'CARREFOUR BR'));
        $manager->persist($assetFactory->makeEntity('CRIV3', Asset::TYPE_STOCK, 'ALFA FINANC'));
        $manager->persist($assetFactory->makeEntity('CRIV4', Asset::TYPE_STOCK, 'ALFA FINANC'));
        $manager->persist($assetFactory->makeEntity('CRPG3', Asset::TYPE_STOCK, 'CRISTAL'));
        $manager->persist($assetFactory->makeEntity('CRPG5', Asset::TYPE_STOCK, 'CRISTAL'));
        $manager->persist($assetFactory->makeEntity('CRPG6', Asset::TYPE_STOCK, 'CRISTAL'));
        $manager->persist($assetFactory->makeEntity('CSAB3', Asset::TYPE_STOCK, 'SEG AL BAHIA'));
        $manager->persist($assetFactory->makeEntity('CSAB4', Asset::TYPE_STOCK, 'SEG AL BAHIA'));
        $manager->persist($assetFactory->makeEntity('CSAN3', Asset::TYPE_STOCK, 'COSAN'));
        $manager->persist($assetFactory->makeEntity('CSMG3', Asset::TYPE_STOCK, 'COPASA'));
        $manager->persist($assetFactory->makeEntity('CSNA3', Asset::TYPE_STOCK, 'SID NACIONAL'));
        $manager->persist($assetFactory->makeEntity('CSRN3', Asset::TYPE_STOCK, 'COSERN'));
        $manager->persist($assetFactory->makeEntity('CSRN5', Asset::TYPE_STOCK, 'COSERN'));
        $manager->persist($assetFactory->makeEntity('CSRN6', Asset::TYPE_STOCK, 'COSERN'));
        $manager->persist($assetFactory->makeEntity('CTCA3', Asset::TYPE_STOCK, 'CTC S.A.'));
        $manager->persist($assetFactory->makeEntity('CTKA3', Asset::TYPE_STOCK, 'KARSTEN'));
        $manager->persist($assetFactory->makeEntity('CTKA4', Asset::TYPE_STOCK, 'KARSTEN'));
        $manager->persist($assetFactory->makeEntity('CTNM3', Asset::TYPE_STOCK, 'COTEMINAS'));
        $manager->persist($assetFactory->makeEntity('CTNM4', Asset::TYPE_STOCK, 'COTEMINAS'));
        $manager->persist($assetFactory->makeEntity('CTSA3', Asset::TYPE_STOCK, 'SANTANENSE'));
        $manager->persist($assetFactory->makeEntity('CTSA4', Asset::TYPE_STOCK, 'SANTANENSE'));
        $manager->persist($assetFactory->makeEntity('CTSA8', Asset::TYPE_STOCK, 'SANTANENSE'));
        $manager->persist($assetFactory->makeEntity('CURY3', Asset::TYPE_STOCK, 'CURY S/A'));
        $manager->persist($assetFactory->makeEntity('CVCB3', Asset::TYPE_STOCK, 'CVC BRASIL'));
        $manager->persist($assetFactory->makeEntity('CYRE3', Asset::TYPE_STOCK, 'CYRELA REALT'));
        $manager->persist($assetFactory->makeEntity('DASA3', Asset::TYPE_STOCK, 'DASA'));
        $manager->persist($assetFactory->makeEntity('DIRR3', Asset::TYPE_STOCK, 'DIRECIONAL'));
        $manager->persist($assetFactory->makeEntity('DMMO3', Asset::TYPE_STOCK, 'DOMMO'));
        $manager->persist($assetFactory->makeEntity('DMVF3', Asset::TYPE_STOCK, 'D1000VFARMA'));
        $manager->persist($assetFactory->makeEntity('DOHL3', Asset::TYPE_STOCK, 'DOHLER'));
        $manager->persist($assetFactory->makeEntity('DOHL4', Asset::TYPE_STOCK, 'DOHLER'));
        $manager->persist($assetFactory->makeEntity('DTCY3', Asset::TYPE_STOCK, 'DTCOM-DIRECT'));
        $manager->persist($assetFactory->makeEntity('DTCY4', Asset::TYPE_STOCK, 'DTCOM-DIRECT'));
        $manager->persist($assetFactory->makeEntity('DTEX3', Asset::TYPE_STOCK, 'DURATEX'));
        $manager->persist($assetFactory->makeEntity('EALT3', Asset::TYPE_STOCK, 'ACO ALTONA'));
        $manager->persist($assetFactory->makeEntity('EALT4', Asset::TYPE_STOCK, 'ACO ALTONA'));
        $manager->persist($assetFactory->makeEntity('ECOR3', Asset::TYPE_STOCK, 'ECORODOVIAS'));
        $manager->persist($assetFactory->makeEntity('ECPR3', Asset::TYPE_STOCK, 'ENCORPAR'));
        $manager->persist($assetFactory->makeEntity('ECPR4', Asset::TYPE_STOCK, 'ENCORPAR'));
        $manager->persist($assetFactory->makeEntity('EEEL3', Asset::TYPE_STOCK, 'CEEE-GT'));
        $manager->persist($assetFactory->makeEntity('EEEL4', Asset::TYPE_STOCK, 'CEEE-GT'));
        $manager->persist($assetFactory->makeEntity('EGIE3', Asset::TYPE_STOCK, 'ENGIE BRASIL'));
        $manager->persist($assetFactory->makeEntity('EKTR3', Asset::TYPE_STOCK, 'ELEKTRO'));
        $manager->persist($assetFactory->makeEntity('EKTR4', Asset::TYPE_STOCK, 'ELEKTRO'));
        $manager->persist($assetFactory->makeEntity('ELEK3', Asset::TYPE_STOCK, 'ELEKEIROZ'));
        $manager->persist($assetFactory->makeEntity('ELEK4', Asset::TYPE_STOCK, 'ELEKEIROZ'));
        $manager->persist($assetFactory->makeEntity('ELET3', Asset::TYPE_STOCK, 'ELETROBRAS'));
        $manager->persist($assetFactory->makeEntity('ELET5', Asset::TYPE_STOCK, 'ELETROBRAS'));
        $manager->persist($assetFactory->makeEntity('ELET6', Asset::TYPE_STOCK, 'ELETROBRAS'));
        $manager->persist($assetFactory->makeEntity('EMAE3', Asset::TYPE_STOCK, 'EMAE'));
        $manager->persist($assetFactory->makeEntity('EMAE4', Asset::TYPE_STOCK, 'EMAE'));
        $manager->persist($assetFactory->makeEntity('EMBR3', Asset::TYPE_STOCK, 'EMBRAER'));
        $manager->persist($assetFactory->makeEntity('ENAT3', Asset::TYPE_STOCK, 'ENAUTA PART'));
        $manager->persist($assetFactory->makeEntity('ENBR3', Asset::TYPE_STOCK, 'ENERGIAS BR'));
        $manager->persist($assetFactory->makeEntity('ENEV3', Asset::TYPE_STOCK, 'ENEVA'));
        $manager->persist($assetFactory->makeEntity('ENGI11', Asset::TYPE_STOCK, 'ENERGISA'));
        $manager->persist($assetFactory->makeEntity('ENGI3', Asset::TYPE_STOCK, 'ENERGISA'));
        $manager->persist($assetFactory->makeEntity('ENGI4', Asset::TYPE_STOCK, 'ENERGISA'));
        $manager->persist($assetFactory->makeEntity('ENJU3', Asset::TYPE_STOCK, 'ENJOEI'));
        $manager->persist($assetFactory->makeEntity('ENMT3', Asset::TYPE_STOCK, 'ENERGISA MT'));
        $manager->persist($assetFactory->makeEntity('ENMT4', Asset::TYPE_STOCK, 'ENERGISA MT'));
        $manager->persist($assetFactory->makeEntity('EQPA3', Asset::TYPE_STOCK, 'EQTL PARA'));
        $manager->persist($assetFactory->makeEntity('EQPA5', Asset::TYPE_STOCK, 'EQTL PARA'));
        $manager->persist($assetFactory->makeEntity('EQPA6', Asset::TYPE_STOCK, 'EQTL PARA'));
        $manager->persist($assetFactory->makeEntity('EQPA7', Asset::TYPE_STOCK, 'EQTL PARA'));
        $manager->persist($assetFactory->makeEntity('EQTL3', Asset::TYPE_STOCK, 'EQUATORIAL'));
        $manager->persist($assetFactory->makeEntity('ESTR3', Asset::TYPE_STOCK, 'ESTRELA'));
        $manager->persist($assetFactory->makeEntity('ESTR4', Asset::TYPE_STOCK, 'ESTRELA'));
        $manager->persist($assetFactory->makeEntity('ETER3', Asset::TYPE_STOCK, 'ETERNIT'));
        $manager->persist($assetFactory->makeEntity('EUCA3', Asset::TYPE_STOCK, 'EUCATEX'));
        $manager->persist($assetFactory->makeEntity('EUCA4', Asset::TYPE_STOCK, 'EUCATEX'));
        $manager->persist($assetFactory->makeEntity('EVEN3', Asset::TYPE_STOCK, 'EVEN'));
        $manager->persist($assetFactory->makeEntity('EZTC3', Asset::TYPE_STOCK, 'EZTEC'));
        $manager->persist($assetFactory->makeEntity('FESA3', Asset::TYPE_STOCK, 'FERBASA'));
        $manager->persist($assetFactory->makeEntity('FESA4', Asset::TYPE_STOCK, 'FERBASA'));
        $manager->persist($assetFactory->makeEntity('FHER3', Asset::TYPE_STOCK, 'FER HERINGER'));
        $manager->persist($assetFactory->makeEntity('FIGE3', Asset::TYPE_STOCK, 'INVEST BEMGE'));
        $manager->persist($assetFactory->makeEntity('FIGE4', Asset::TYPE_STOCK, 'INVEST BEMGE'));
        $manager->persist($assetFactory->makeEntity('FLEX3', Asset::TYPE_STOCK, 'FLEX S/A'));
        $manager->persist($assetFactory->makeEntity('FLRY3', Asset::TYPE_STOCK, 'FLEURY'));
        $manager->persist($assetFactory->makeEntity('FNCN3', Asset::TYPE_STOCK, 'FINANSINOS'));
        $manager->persist($assetFactory->makeEntity('FRAS3', Asset::TYPE_STOCK, 'FRAS-LE'));
        $manager->persist($assetFactory->makeEntity('FRIO3', Asset::TYPE_STOCK, 'METALFRIO'));
        $manager->persist($assetFactory->makeEntity('FRTA3', Asset::TYPE_STOCK, 'POMIFRUTAS'));
        $manager->persist($assetFactory->makeEntity('GEPA3', Asset::TYPE_STOCK, 'GER PARANAP'));
        $manager->persist($assetFactory->makeEntity('GEPA4', Asset::TYPE_STOCK, 'GER PARANAP'));
        $manager->persist($assetFactory->makeEntity('GFSA3', Asset::TYPE_STOCK, 'GAFISA'));
        $manager->persist($assetFactory->makeEntity('GGBR3', Asset::TYPE_STOCK, 'GERDAU'));
        $manager->persist($assetFactory->makeEntity('GGBR4', Asset::TYPE_STOCK, 'GERDAU'));
        $manager->persist($assetFactory->makeEntity('GMAT3', Asset::TYPE_STOCK, 'GRUPO MATEUS'));
        $manager->persist($assetFactory->makeEntity('GNDI3', Asset::TYPE_STOCK, 'INTERMEDICA'));
        $manager->persist($assetFactory->makeEntity('GOAU3', Asset::TYPE_STOCK, 'GERDAU MET'));
        $manager->persist($assetFactory->makeEntity('GOAU4', Asset::TYPE_STOCK, 'GERDAU MET'));
        $manager->persist($assetFactory->makeEntity('GOLL4', Asset::TYPE_STOCK, 'GOL'));
        $manager->persist($assetFactory->makeEntity('GPAR3', Asset::TYPE_STOCK, 'CELGPAR'));
        $manager->persist($assetFactory->makeEntity('GPCP3', Asset::TYPE_STOCK, 'GPC PART'));
        $manager->persist($assetFactory->makeEntity('GPCP4', Asset::TYPE_STOCK, 'GPC PART'));
        $manager->persist($assetFactory->makeEntity('GPIV33', Asset::TYPE_STOCK, 'GP INVEST'));
        $manager->persist($assetFactory->makeEntity('GRND3', Asset::TYPE_STOCK, 'GRENDENE'));
        $manager->persist($assetFactory->makeEntity('GSHP3', Asset::TYPE_STOCK, 'GENERALSHOPP'));
        $manager->persist($assetFactory->makeEntity('GUAR3', Asset::TYPE_STOCK, 'GUARARAPES'));
        $manager->persist($assetFactory->makeEntity('HAGA3', Asset::TYPE_STOCK, 'HAGA S/A'));
        $manager->persist($assetFactory->makeEntity('HAGA4', Asset::TYPE_STOCK, 'HAGA S/A'));
        $manager->persist($assetFactory->makeEntity('HAPV3', Asset::TYPE_STOCK, 'HAPVIDA'));
        $manager->persist($assetFactory->makeEntity('HBOR3', Asset::TYPE_STOCK, 'HELBOR'));
        $manager->persist($assetFactory->makeEntity('HBSA3', Asset::TYPE_STOCK, 'HIDROVIAS'));
        $manager->persist($assetFactory->makeEntity('HBTS3', Asset::TYPE_STOCK, 'HABITASUL'));
        $manager->persist($assetFactory->makeEntity('HBTS5', Asset::TYPE_STOCK, 'HABITASUL'));
        $manager->persist($assetFactory->makeEntity('HBTS6', Asset::TYPE_STOCK, 'HABITASUL'));
        $manager->persist($assetFactory->makeEntity('HCBR3', Asset::TYPE_STOCK, 'BR HOME'));
        $manager->persist($assetFactory->makeEntity('HETA3', Asset::TYPE_STOCK, 'HERCULES'));
        $manager->persist($assetFactory->makeEntity('HETA4', Asset::TYPE_STOCK, 'HERCULES'));
        $manager->persist($assetFactory->makeEntity('HGTX3', Asset::TYPE_STOCK, 'CIA HERING'));
        $manager->persist($assetFactory->makeEntity('HOOT3', Asset::TYPE_STOCK, 'HOTEIS OTHON'));
        $manager->persist($assetFactory->makeEntity('HOOT4', Asset::TYPE_STOCK, 'HOTEIS OTHON'));
        $manager->persist($assetFactory->makeEntity('HYPE3', Asset::TYPE_STOCK, 'HYPERA'));
        $manager->persist($assetFactory->makeEntity('IGBR3', Asset::TYPE_STOCK, 'IGB S/A'));
        $manager->persist($assetFactory->makeEntity('IGSN3', Asset::TYPE_STOCK, 'IGUA SA'));
        $manager->persist($assetFactory->makeEntity('IGTA3', Asset::TYPE_STOCK, 'IGUATEMI'));
        $manager->persist($assetFactory->makeEntity('INEP3', Asset::TYPE_STOCK, 'INEPAR'));
        $manager->persist($assetFactory->makeEntity('INEP4', Asset::TYPE_STOCK, 'INEPAR'));
        $manager->persist($assetFactory->makeEntity('INNT3', Asset::TYPE_STOCK, 'INTER SA'));
        $manager->persist($assetFactory->makeEntity('IRBR3', Asset::TYPE_STOCK, 'IRBBRASIL RE'));
        $manager->persist($assetFactory->makeEntity('ITEC3', Asset::TYPE_STOCK, 'ITAUTEC'));
        $manager->persist($assetFactory->makeEntity('ITSA3', Asset::TYPE_STOCK, 'ITAUSA'));
        $manager->persist($assetFactory->makeEntity('ITSA4', Asset::TYPE_STOCK, 'ITAUSA'));
        $manager->persist($assetFactory->makeEntity('ITUB3', Asset::TYPE_STOCK, 'ITAUUNIBANCO'));
        $manager->persist($assetFactory->makeEntity('ITUB4', Asset::TYPE_STOCK, 'ITAUUNIBANCO'));
        $manager->persist($assetFactory->makeEntity('JBDU3', Asset::TYPE_STOCK, 'J B DUARTE'));
        $manager->persist($assetFactory->makeEntity('JBDU4', Asset::TYPE_STOCK, 'J B DUARTE'));
        $manager->persist($assetFactory->makeEntity('JBSS3', Asset::TYPE_STOCK, 'JBS'));
        $manager->persist($assetFactory->makeEntity('JFEN3', Asset::TYPE_STOCK, 'JOAO FORTES'));
        $manager->persist($assetFactory->makeEntity('JHSF3', Asset::TYPE_STOCK, 'JHSF PART'));
        $manager->persist($assetFactory->makeEntity('JOPA3', Asset::TYPE_STOCK, 'JOSAPAR'));
        $manager->persist($assetFactory->makeEntity('JOPA4', Asset::TYPE_STOCK, 'JOSAPAR'));
        $manager->persist($assetFactory->makeEntity('JPSA3', Asset::TYPE_STOCK, 'JEREISSATI'));
        $manager->persist($assetFactory->makeEntity('KEPL3', Asset::TYPE_STOCK, 'KEPLER WEBER'));
        $manager->persist($assetFactory->makeEntity('KLBN11', Asset::TYPE_STOCK, 'KLABIN S/A'));
        $manager->persist($assetFactory->makeEntity('KLBN3', Asset::TYPE_STOCK, 'KLABIN S/A'));
        $manager->persist($assetFactory->makeEntity('KLBN4', Asset::TYPE_STOCK, 'KLABIN S/A'));
        $manager->persist($assetFactory->makeEntity('LAME3', Asset::TYPE_STOCK, 'LOJAS AMERIC'));
        $manager->persist($assetFactory->makeEntity('LAME4', Asset::TYPE_STOCK, 'LOJAS AMERIC'));
        $manager->persist($assetFactory->makeEntity('LAVV3', Asset::TYPE_STOCK, 'LAVVI'));
        $manager->persist($assetFactory->makeEntity('LCAM3', Asset::TYPE_STOCK, 'LOCAMERICA'));
        $manager->persist($assetFactory->makeEntity('LEVE3', Asset::TYPE_STOCK, 'METAL LEVE'));
        $manager->persist($assetFactory->makeEntity('LHER3', Asset::TYPE_STOCK, 'LOJAS HERING'));
        $manager->persist($assetFactory->makeEntity('LHER4', Asset::TYPE_STOCK, 'LOJAS HERING'));
        $manager->persist($assetFactory->makeEntity('LIGT3', Asset::TYPE_STOCK, 'LIGHT S/A'));
        $manager->persist($assetFactory->makeEntity('LINX3', Asset::TYPE_STOCK, 'LINX'));
        $manager->persist($assetFactory->makeEntity('LIPR3', Asset::TYPE_STOCK, 'ELETROPAR'));
        $manager->persist($assetFactory->makeEntity('LJQQ3', Asset::TYPE_STOCK, 'QUERO-QUERO'));
        $manager->persist($assetFactory->makeEntity('LMED3', Asset::TYPE_STOCK, 'LIFEMED'));
        $manager->persist($assetFactory->makeEntity('LOGG3', Asset::TYPE_STOCK, 'LOG COM PROP'));
        $manager->persist($assetFactory->makeEntity('LOGN3', Asset::TYPE_STOCK, 'LOG-IN'));
        $manager->persist($assetFactory->makeEntity('LPSB3', Asset::TYPE_STOCK, 'LOPES BRASIL'));
        $manager->persist($assetFactory->makeEntity('LREN3', Asset::TYPE_STOCK, 'LOJAS RENNER'));
        $manager->persist($assetFactory->makeEntity('LUPA3', Asset::TYPE_STOCK, 'LUPATECH'));
        $manager->persist($assetFactory->makeEntity('LUXM3', Asset::TYPE_STOCK, 'TREVISA'));
        $manager->persist($assetFactory->makeEntity('LUXM4', Asset::TYPE_STOCK, 'TREVISA'));
        $manager->persist($assetFactory->makeEntity('LWSA3', Asset::TYPE_STOCK, 'LOCAWEB'));
        $manager->persist($assetFactory->makeEntity('MAPT3', Asset::TYPE_STOCK, 'CEMEPE'));
        $manager->persist($assetFactory->makeEntity('MAPT4', Asset::TYPE_STOCK, 'CEMEPE'));
        $manager->persist($assetFactory->makeEntity('MDIA3', Asset::TYPE_STOCK, 'M.DIASBRANCO'));
        $manager->persist($assetFactory->makeEntity('MDNE3', Asset::TYPE_STOCK, 'MOURA DUBEUX'));
        $manager->persist($assetFactory->makeEntity('MEAL3', Asset::TYPE_STOCK, 'IMC S/A'));
        $manager->persist($assetFactory->makeEntity('MELK3', Asset::TYPE_STOCK, 'MELNICK'));
        $manager->persist($assetFactory->makeEntity('MERC3', Asset::TYPE_STOCK, 'MERC FINANC'));
        $manager->persist($assetFactory->makeEntity('MERC4', Asset::TYPE_STOCK, 'MERC FINANC'));
        $manager->persist($assetFactory->makeEntity('MGEL3', Asset::TYPE_STOCK, 'MANGELS INDL'));
        $manager->persist($assetFactory->makeEntity('MGEL4', Asset::TYPE_STOCK, 'MANGELS INDL'));
        $manager->persist($assetFactory->makeEntity('MGLU3', Asset::TYPE_STOCK, 'MAGAZ LUIZA'));
        $manager->persist($assetFactory->makeEntity('MILS3', Asset::TYPE_STOCK, 'MILLS'));
        $manager->persist($assetFactory->makeEntity('MMAQ3', Asset::TYPE_STOCK, 'MINASMAQUINA'));
        $manager->persist($assetFactory->makeEntity('MMAQ4', Asset::TYPE_STOCK, 'MINASMAQUINA'));
        $manager->persist($assetFactory->makeEntity('MMXM3', Asset::TYPE_STOCK, 'MMX MINER'));
        $manager->persist($assetFactory->makeEntity('MNDL3', Asset::TYPE_STOCK, 'MUNDIAL'));
        $manager->persist($assetFactory->makeEntity('MNPR3', Asset::TYPE_STOCK, 'MINUPAR'));
        $manager->persist($assetFactory->makeEntity('MOAR3', Asset::TYPE_STOCK, 'MONT ARANHA'));
        $manager->persist($assetFactory->makeEntity('MOVI3', Asset::TYPE_STOCK, 'MOVIDA'));
        $manager->persist($assetFactory->makeEntity('MPLU3', Asset::TYPE_STOCK, 'MULTIPLUS'));
        $manager->persist($assetFactory->makeEntity('MRFG3', Asset::TYPE_STOCK, 'MARFRIG'));
        $manager->persist($assetFactory->makeEntity('MRVE3', Asset::TYPE_STOCK, 'MRV'));
        $manager->persist($assetFactory->makeEntity('MSPA3', Asset::TYPE_STOCK, 'MELHOR SP'));
        $manager->persist($assetFactory->makeEntity('MSPA4', Asset::TYPE_STOCK, 'MELHOR SP'));
        $manager->persist($assetFactory->makeEntity('MSRO3', Asset::TYPE_STOCK, 'MAESTROLOC'));
        $manager->persist($assetFactory->makeEntity('MTIG3', Asset::TYPE_STOCK, 'METAL IGUACU'));
        $manager->persist($assetFactory->makeEntity('MTIG4', Asset::TYPE_STOCK, 'METAL IGUACU'));
        $manager->persist($assetFactory->makeEntity('MTRE3', Asset::TYPE_STOCK, 'MITRE REALTY'));
        $manager->persist($assetFactory->makeEntity('MTSA3', Asset::TYPE_STOCK, 'METISA'));
        $manager->persist($assetFactory->makeEntity('MTSA4', Asset::TYPE_STOCK, 'METISA'));
        $manager->persist($assetFactory->makeEntity('MULT3', Asset::TYPE_STOCK, 'MULTIPLAN'));
        $manager->persist($assetFactory->makeEntity('MWET3', Asset::TYPE_STOCK, 'WETZEL S/A'));
        $manager->persist($assetFactory->makeEntity('MWET4', Asset::TYPE_STOCK, 'WETZEL S/A'));
        $manager->persist($assetFactory->makeEntity('MYPK3', Asset::TYPE_STOCK, 'IOCHP-MAXION'));
        $manager->persist($assetFactory->makeEntity('NAFG3', Asset::TYPE_STOCK, 'NADIR FIGUEI'));
        $manager->persist($assetFactory->makeEntity('NAFG4', Asset::TYPE_STOCK, 'NADIR FIGUEI'));
        $manager->persist($assetFactory->makeEntity('NEMO3', Asset::TYPE_STOCK, 'SUZANO HOLD'));
        $manager->persist($assetFactory->makeEntity('NEMO5', Asset::TYPE_STOCK, 'SUZANO HOLD'));
        $manager->persist($assetFactory->makeEntity('NEMO6', Asset::TYPE_STOCK, 'SUZANO HOLD'));
        $manager->persist($assetFactory->makeEntity('NEOE3', Asset::TYPE_STOCK, 'NEOENERGIA'));
        $manager->persist($assetFactory->makeEntity('NGRD3', Asset::TYPE_STOCK, 'NEOGRID'));
        $manager->persist($assetFactory->makeEntity('NORD3', Asset::TYPE_STOCK, 'NORDON MET'));
        $manager->persist($assetFactory->makeEntity('NRTQ3', Asset::TYPE_STOCK, 'NORTCQUIMICA'));
        $manager->persist($assetFactory->makeEntity('NTCO3', Asset::TYPE_STOCK, 'GRUPO NATURA'));
        $manager->persist($assetFactory->makeEntity('ODER3', Asset::TYPE_STOCK, 'ODERICH'));
        $manager->persist($assetFactory->makeEntity('ODER4', Asset::TYPE_STOCK, 'ODERICH'));
        $manager->persist($assetFactory->makeEntity('ODPV3', Asset::TYPE_STOCK, 'ODONTOPREV'));
        $manager->persist($assetFactory->makeEntity('OFSA3', Asset::TYPE_STOCK, 'OUROFINO S/A'));
        $manager->persist($assetFactory->makeEntity('OIBR3', Asset::TYPE_STOCK, 'OI'));
        $manager->persist($assetFactory->makeEntity('OIBR4', Asset::TYPE_STOCK, 'OI'));
        $manager->persist($assetFactory->makeEntity('OMGE3', Asset::TYPE_STOCK, 'OMEGA GER'));
        $manager->persist($assetFactory->makeEntity('OSXB3', Asset::TYPE_STOCK, 'OSX BRASIL'));
        $manager->persist($assetFactory->makeEntity('PACF3', Asset::TYPE_STOCK, 'PACIFIC RDSL'));
        $manager->persist($assetFactory->makeEntity('PARD3', Asset::TYPE_STOCK, 'IHPARDINI'));
        $manager->persist($assetFactory->makeEntity('PATI3', Asset::TYPE_STOCK, 'PANATLANTICA'));
        $manager->persist($assetFactory->makeEntity('PATI4', Asset::TYPE_STOCK, 'PANATLANTICA'));
        $manager->persist($assetFactory->makeEntity('PCAR3', Asset::TYPE_STOCK, 'P.ACUCAR-CBD'));
        $manager->persist($assetFactory->makeEntity('PDGR3', Asset::TYPE_STOCK, 'PDG REALT'));
        $manager->persist($assetFactory->makeEntity('PDTC3', Asset::TYPE_STOCK, 'PADTEC'));
        $manager->persist($assetFactory->makeEntity('PEAB3', Asset::TYPE_STOCK, 'PAR AL BAHIA'));
        $manager->persist($assetFactory->makeEntity('PEAB4', Asset::TYPE_STOCK, 'PAR AL BAHIA'));
        $manager->persist($assetFactory->makeEntity('PETR3', Asset::TYPE_STOCK, 'PETROBRAS'));
        $manager->persist($assetFactory->makeEntity('PETR4', Asset::TYPE_STOCK, 'PETROBRAS'));
        $manager->persist($assetFactory->makeEntity('PETZ3', Asset::TYPE_STOCK, 'PETZ'));
        $manager->persist($assetFactory->makeEntity('PFRM3', Asset::TYPE_STOCK, 'PROFARMA'));
        $manager->persist($assetFactory->makeEntity('PGMN3', Asset::TYPE_STOCK, 'PAGUE MENOS'));
        $manager->persist($assetFactory->makeEntity('PINE3', Asset::TYPE_STOCK, 'PINE'));
        $manager->persist($assetFactory->makeEntity('PINE4', Asset::TYPE_STOCK, 'PINE'));
        $manager->persist($assetFactory->makeEntity('PLAS3', Asset::TYPE_STOCK, 'PLASCAR PART'));
        $manager->persist($assetFactory->makeEntity('PLPL3', Asset::TYPE_STOCK, 'PLANOEPLANO'));
        $manager->persist($assetFactory->makeEntity('PMAM3', Asset::TYPE_STOCK, 'PARANAPANEMA'));
        $manager->persist($assetFactory->makeEntity('PNVL3', Asset::TYPE_STOCK, 'DIMED'));
        $manager->persist($assetFactory->makeEntity('PNVL4', Asset::TYPE_STOCK, 'DIMED'));
        $manager->persist($assetFactory->makeEntity('POMO3', Asset::TYPE_STOCK, 'MARCOPOLO'));
        $manager->persist($assetFactory->makeEntity('POMO4', Asset::TYPE_STOCK, 'MARCOPOLO'));
        $manager->persist($assetFactory->makeEntity('POSI3', Asset::TYPE_STOCK, 'POSITIVO TEC'));
        $manager->persist($assetFactory->makeEntity('PPAR3', Asset::TYPE_STOCK, 'POLPAR'));
        $manager->persist($assetFactory->makeEntity('PPLA11', Asset::TYPE_STOCK, 'PPLA'));
        $manager->persist($assetFactory->makeEntity('PRIO3', Asset::TYPE_STOCK, 'PETRORIO'));
        $manager->persist($assetFactory->makeEntity('PRNR3', Asset::TYPE_STOCK, 'PRINER'));
        $manager->persist($assetFactory->makeEntity('PSSA3', Asset::TYPE_STOCK, 'PORTO SEGURO'));
        $manager->persist($assetFactory->makeEntity('PTBL3', Asset::TYPE_STOCK, 'PORTOBELLO'));
        $manager->persist($assetFactory->makeEntity('PTCA11', Asset::TYPE_STOCK, 'PRATICA'));
        $manager->persist($assetFactory->makeEntity('PTCA3', Asset::TYPE_STOCK, 'PRATICA'));
        $manager->persist($assetFactory->makeEntity('PTNT3', Asset::TYPE_STOCK, 'PETTENATI'));
        $manager->persist($assetFactory->makeEntity('PTNT4', Asset::TYPE_STOCK, 'PETTENATI'));
        $manager->persist($assetFactory->makeEntity('QUAL3', Asset::TYPE_STOCK, 'QUALICORP'));
        $manager->persist($assetFactory->makeEntity('QUSW3', Asset::TYPE_STOCK, 'QUALITY SOFT'));
        $manager->persist($assetFactory->makeEntity('RADL3', Asset::TYPE_STOCK, 'RAIADROGASIL'));
        $manager->persist($assetFactory->makeEntity('RAIL3', Asset::TYPE_STOCK, 'RUMO S.A.'));
        $manager->persist($assetFactory->makeEntity('RANI3', Asset::TYPE_STOCK, 'IRANI'));
        $manager->persist($assetFactory->makeEntity('RAPT3', Asset::TYPE_STOCK, 'RANDON PART'));
        $manager->persist($assetFactory->makeEntity('RAPT4', Asset::TYPE_STOCK, 'RANDON PART'));
        $manager->persist($assetFactory->makeEntity('RCSL3', Asset::TYPE_STOCK, 'RECRUSUL'));
        $manager->persist($assetFactory->makeEntity('RCSL4', Asset::TYPE_STOCK, 'RECRUSUL'));
        $manager->persist($assetFactory->makeEntity('RDNI3', Asset::TYPE_STOCK, 'RNI'));
        $manager->persist($assetFactory->makeEntity('RDOR3', Asset::TYPE_STOCK, 'REDE D OR'));
        $manager->persist($assetFactory->makeEntity('REDE3', Asset::TYPE_STOCK, 'REDE ENERGIA'));
        $manager->persist($assetFactory->makeEntity('RENT3', Asset::TYPE_STOCK, 'LOCALIZA'));
        $manager->persist($assetFactory->makeEntity('RLOG3', Asset::TYPE_STOCK, 'COSAN LOG'));
        $manager->persist($assetFactory->makeEntity('RNEW11', Asset::TYPE_STOCK, 'RENOVA'));
        $manager->persist($assetFactory->makeEntity('RNEW3', Asset::TYPE_STOCK, 'RENOVA'));
        $manager->persist($assetFactory->makeEntity('RNEW4', Asset::TYPE_STOCK, 'RENOVA'));
        $manager->persist($assetFactory->makeEntity('ROMI3', Asset::TYPE_STOCK, 'INDS ROMI'));
        $manager->persist($assetFactory->makeEntity('RPAD3', Asset::TYPE_STOCK, 'ALFA HOLDING'));
        $manager->persist($assetFactory->makeEntity('RPAD5', Asset::TYPE_STOCK, 'ALFA HOLDING'));
        $manager->persist($assetFactory->makeEntity('RPAD6', Asset::TYPE_STOCK, 'ALFA HOLDING'));
        $manager->persist($assetFactory->makeEntity('RPMG3', Asset::TYPE_STOCK, 'PET MANGUINH'));
        $manager->persist($assetFactory->makeEntity('RRRP3', Asset::TYPE_STOCK, '3R PETROLEUM'));
        $manager->persist($assetFactory->makeEntity('RSID3', Asset::TYPE_STOCK, 'ROSSI RESID'));
        $manager->persist($assetFactory->makeEntity('RSUL3', Asset::TYPE_STOCK, 'RIOSULENSE'));
        $manager->persist($assetFactory->makeEntity('RSUL4', Asset::TYPE_STOCK, 'RIOSULENSE'));
        $manager->persist($assetFactory->makeEntity('SANB11', Asset::TYPE_STOCK, 'SANTANDER BR'));
        $manager->persist($assetFactory->makeEntity('SANB3', Asset::TYPE_STOCK, 'SANTANDER BR'));
        $manager->persist($assetFactory->makeEntity('SANB4', Asset::TYPE_STOCK, 'SANTANDER BR'));
        $manager->persist($assetFactory->makeEntity('SAPR11', Asset::TYPE_STOCK, 'SANEPAR'));
        $manager->persist($assetFactory->makeEntity('SAPR3', Asset::TYPE_STOCK, 'SANEPAR'));
        $manager->persist($assetFactory->makeEntity('SAPR4', Asset::TYPE_STOCK, 'SANEPAR'));
        $manager->persist($assetFactory->makeEntity('SBSP3', Asset::TYPE_STOCK, 'SABESP'));
        $manager->persist($assetFactory->makeEntity('SCAR3', Asset::TYPE_STOCK, 'SAO CARLOS'));
        $manager->persist($assetFactory->makeEntity('SEDU3', Asset::TYPE_STOCK, 'SOMOS EDUCA'));
        $manager->persist($assetFactory->makeEntity('SEER3', Asset::TYPE_STOCK, 'SER EDUCA'));
        $manager->persist($assetFactory->makeEntity('SEQL3', Asset::TYPE_STOCK, 'SEQUOIA LOG'));
        $manager->persist($assetFactory->makeEntity('SGPS3', Asset::TYPE_STOCK, 'SPRINGS'));
        $manager->persist($assetFactory->makeEntity('SHOW3', Asset::TYPE_STOCK, 'TIME FOR FUN'));
        $manager->persist($assetFactory->makeEntity('SHUL3', Asset::TYPE_STOCK, 'SCHULZ'));
        $manager->persist($assetFactory->makeEntity('SHUL4', Asset::TYPE_STOCK, 'SCHULZ'));
        $manager->persist($assetFactory->makeEntity('SIMH3', Asset::TYPE_STOCK, 'SIMPAR'));
        $manager->persist($assetFactory->makeEntity('SLCE3', Asset::TYPE_STOCK, 'SLC AGRICOLA'));
        $manager->persist($assetFactory->makeEntity('SLED3', Asset::TYPE_STOCK, 'SARAIVA LIVR'));
        $manager->persist($assetFactory->makeEntity('SLED4', Asset::TYPE_STOCK, 'SARAIVA LIVR'));
        $manager->persist($assetFactory->makeEntity('SMFT3', Asset::TYPE_STOCK, 'SMART FIT'));
        $manager->persist($assetFactory->makeEntity('SMLS3', Asset::TYPE_STOCK, 'SMILES'));
        $manager->persist($assetFactory->makeEntity('SMTO3', Asset::TYPE_STOCK, 'SAO MARTINHO'));
        $manager->persist($assetFactory->makeEntity('SNSY3', Asset::TYPE_STOCK, 'SANSUY'));
        $manager->persist($assetFactory->makeEntity('SNSY5', Asset::TYPE_STOCK, 'SANSUY'));
        $manager->persist($assetFactory->makeEntity('SNSY6', Asset::TYPE_STOCK, 'SANSUY'));
        $manager->persist($assetFactory->makeEntity('SOMA3', Asset::TYPE_STOCK, 'GRUPO SOMA'));
        $manager->persist($assetFactory->makeEntity('SOND3', Asset::TYPE_STOCK, 'SONDOTECNICA'));
        $manager->persist($assetFactory->makeEntity('SOND5', Asset::TYPE_STOCK, 'SONDOTECNICA'));
        $manager->persist($assetFactory->makeEntity('SOND6', Asset::TYPE_STOCK, 'SONDOTECNICA'));
        $manager->persist($assetFactory->makeEntity('SPRI3', Asset::TYPE_STOCK, 'SPRINGER'));
        $manager->persist($assetFactory->makeEntity('SPRI5', Asset::TYPE_STOCK, 'SPRINGER'));
        $manager->persist($assetFactory->makeEntity('SPRI6', Asset::TYPE_STOCK, 'SPRINGER'));
        $manager->persist($assetFactory->makeEntity('SQIA3', Asset::TYPE_STOCK, 'SINQIA'));
        $manager->persist($assetFactory->makeEntity('STBP3', Asset::TYPE_STOCK, 'SANTOS BRP'));
        $manager->persist($assetFactory->makeEntity('STKF3', Asset::TYPE_STOCK, 'STATKRAFT'));
        $manager->persist($assetFactory->makeEntity('STTR3', Asset::TYPE_STOCK, 'STARA'));
        $manager->persist($assetFactory->makeEntity('SULA11', Asset::TYPE_STOCK, 'SUL AMERICA'));
        $manager->persist($assetFactory->makeEntity('SULA3', Asset::TYPE_STOCK, 'SUL AMERICA'));
        $manager->persist($assetFactory->makeEntity('SULA4', Asset::TYPE_STOCK, 'SUL AMERICA'));
        $manager->persist($assetFactory->makeEntity('SUZB3', Asset::TYPE_STOCK, 'SUZANO S.A.'));
        $manager->persist($assetFactory->makeEntity('TAEE11', Asset::TYPE_STOCK, 'TAESA'));
        $manager->persist($assetFactory->makeEntity('TAEE3', Asset::TYPE_STOCK, 'TAESA'));
        $manager->persist($assetFactory->makeEntity('TAEE4', Asset::TYPE_STOCK, 'TAESA'));
        $manager->persist($assetFactory->makeEntity('TASA3', Asset::TYPE_STOCK, 'TAURUS ARMAS'));
        $manager->persist($assetFactory->makeEntity('TASA4', Asset::TYPE_STOCK, 'TAURUS ARMAS'));
        $manager->persist($assetFactory->makeEntity('TCNO3', Asset::TYPE_STOCK, 'TECNOSOLO'));
        $manager->persist($assetFactory->makeEntity('TCNO4', Asset::TYPE_STOCK, 'TECNOSOLO'));
        $manager->persist($assetFactory->makeEntity('TCSA3', Asset::TYPE_STOCK, 'TECNISA'));
        $manager->persist($assetFactory->makeEntity('TECN3', Asset::TYPE_STOCK, 'TECHNOS'));
        $manager->persist($assetFactory->makeEntity('TEKA3', Asset::TYPE_STOCK, 'TEKA'));
        $manager->persist($assetFactory->makeEntity('TEKA4', Asset::TYPE_STOCK, 'TEKA'));
        $manager->persist($assetFactory->makeEntity('TELB3', Asset::TYPE_STOCK, 'TELEBRAS'));
        $manager->persist($assetFactory->makeEntity('TELB4', Asset::TYPE_STOCK, 'TELEBRAS'));
        $manager->persist($assetFactory->makeEntity('TEND3', Asset::TYPE_STOCK, 'TENDA'));
        $manager->persist($assetFactory->makeEntity('TESA3', Asset::TYPE_STOCK, 'TERRA SANTA'));
        $manager->persist($assetFactory->makeEntity('TFCO4', Asset::TYPE_STOCK, 'TRACK FIELD'));
        $manager->persist($assetFactory->makeEntity('TGMA3', Asset::TYPE_STOCK, 'TEGMA'));
        $manager->persist($assetFactory->makeEntity('TIET11', Asset::TYPE_STOCK, 'AES TIETE E'));
        $manager->persist($assetFactory->makeEntity('TIET3', Asset::TYPE_STOCK, 'AES TIETE E'));
        $manager->persist($assetFactory->makeEntity('TIET4', Asset::TYPE_STOCK, 'AES TIETE E'));
        $manager->persist($assetFactory->makeEntity('TIMS3', Asset::TYPE_STOCK, 'TIM'));
        $manager->persist($assetFactory->makeEntity('TKNO3', Asset::TYPE_STOCK, 'TEKNO'));
        $manager->persist($assetFactory->makeEntity('TKNO4', Asset::TYPE_STOCK, 'TEKNO'));
        $manager->persist($assetFactory->makeEntity('TOTS3', Asset::TYPE_STOCK, 'TOTVS'));
        $manager->persist($assetFactory->makeEntity('TOYB3', Asset::TYPE_STOCK, 'TECTOY'));
        $manager->persist($assetFactory->makeEntity('TOYB4', Asset::TYPE_STOCK, 'TECTOY'));
        $manager->persist($assetFactory->makeEntity('TPIS3', Asset::TYPE_STOCK, 'TRIUNFO PART'));
        $manager->persist($assetFactory->makeEntity('TRIS3', Asset::TYPE_STOCK, 'TRISUL'));
        $manager->persist($assetFactory->makeEntity('TRPL3', Asset::TYPE_STOCK, 'TRAN PAULIST'));
        $manager->persist($assetFactory->makeEntity('TRPL4', Asset::TYPE_STOCK, 'TRAN PAULIST'));
        $manager->persist($assetFactory->makeEntity('TRPN3', Asset::TYPE_STOCK, 'TARPON INV'));
        $manager->persist($assetFactory->makeEntity('TUPY3', Asset::TYPE_STOCK, 'TUPY'));
        $manager->persist($assetFactory->makeEntity('UCAS3', Asset::TYPE_STOCK, 'UNICASA'));
        $manager->persist($assetFactory->makeEntity('UGPA3', Asset::TYPE_STOCK, 'ULTRAPAR'));
        $manager->persist($assetFactory->makeEntity('UNIP3', Asset::TYPE_STOCK, 'UNIPAR'));
        $manager->persist($assetFactory->makeEntity('UNIP5', Asset::TYPE_STOCK, 'UNIPAR'));
        $manager->persist($assetFactory->makeEntity('UNIP6', Asset::TYPE_STOCK, 'UNIPAR'));
        $manager->persist($assetFactory->makeEntity('USIM3', Asset::TYPE_STOCK, 'USIMINAS'));
        $manager->persist($assetFactory->makeEntity('USIM5', Asset::TYPE_STOCK, 'USIMINAS'));
        $manager->persist($assetFactory->makeEntity('USIM6', Asset::TYPE_STOCK, 'USIMINAS'));
        $manager->persist($assetFactory->makeEntity('VALE3', Asset::TYPE_STOCK, 'VALE'));
        $manager->persist($assetFactory->makeEntity('VIVA3', Asset::TYPE_STOCK, 'VIVARA S.A.'));
        $manager->persist($assetFactory->makeEntity('VIVR3', Asset::TYPE_STOCK, 'VIVER'));
        $manager->persist($assetFactory->makeEntity('VIVT3', Asset::TYPE_STOCK, 'TELEF BRASIL'));
        $manager->persist($assetFactory->makeEntity('VLID3', Asset::TYPE_STOCK, 'VALID'));
        $manager->persist($assetFactory->makeEntity('VSPT3', Asset::TYPE_STOCK, 'FER C ATLANT'));
        $manager->persist($assetFactory->makeEntity('VSPT4', Asset::TYPE_STOCK, 'FER C ATLANT'));
        $manager->persist($assetFactory->makeEntity('VULC3', Asset::TYPE_STOCK, 'VULCABRAS'));
        $manager->persist($assetFactory->makeEntity('VVAR3', Asset::TYPE_STOCK, 'VIAVAREJO'));
        $manager->persist($assetFactory->makeEntity('WEGE3', Asset::TYPE_STOCK, 'WEG'));
        $manager->persist($assetFactory->makeEntity('WHRL3', Asset::TYPE_STOCK, 'WHIRLPOOL'));
        $manager->persist($assetFactory->makeEntity('WHRL4', Asset::TYPE_STOCK, 'WHIRLPOOL'));
        $manager->persist($assetFactory->makeEntity('WIZS3', Asset::TYPE_STOCK, 'WIZ S.A.'));
        $manager->persist($assetFactory->makeEntity('WLMM3', Asset::TYPE_STOCK, 'WLM IND COM'));
        $manager->persist($assetFactory->makeEntity('WLMM4', Asset::TYPE_STOCK, 'WLM IND COM'));
        $manager->persist($assetFactory->makeEntity('WSON33', Asset::TYPE_STOCK, 'WILSON SONS'));
        $manager->persist($assetFactory->makeEntity('YDUQ3', Asset::TYPE_STOCK, 'YDUQS PART'));

        $manager->flush();
    }
}
