<?php

namespace App\DataFixtures;

use App\Entity\Asset;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AssetsFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $manager->persist($this->makeAsset('WDO',Asset::TYPE_FUTURE_CONTRACT,'Mini Contrato Dólar'));
        $manager->persist($this->makeAsset('WIN',Asset::TYPE_FUTURE_CONTRACT,'Mini Contrato de índice'));
        $manager->persist($this->makeAsset('DOL',Asset::TYPE_FUTURE_CONTRACT,'Contrato de Dólar'));
        $manager->persist($this->makeAsset('IND',Asset::TYPE_FUTURE_CONTRACT,'Contrato de índice'));

        $manager->persist($this->makeAsset('AALR3',Asset::TYPE_STOCK,'ALLIAR'));
        $manager->persist($this->makeAsset('ABCB4',Asset::TYPE_STOCK,'ABC BRASIL'));
        $manager->persist($this->makeAsset('ABEV3',Asset::TYPE_STOCK,'AMBEV S/A'));
        $manager->persist($this->makeAsset('AERI3',Asset::TYPE_STOCK,'AERIS'));
        $manager->persist($this->makeAsset('AFLT3',Asset::TYPE_STOCK,'AFLUENTE T'));
        $manager->persist($this->makeAsset('AGRO3',Asset::TYPE_STOCK,'BRASILAGRO'));
        $manager->persist($this->makeAsset('AHEB3',Asset::TYPE_STOCK,'SPTURIS'));
        $manager->persist($this->makeAsset('AHEB5',Asset::TYPE_STOCK,'SPTURIS'));
        $manager->persist($this->makeAsset('AHEB6',Asset::TYPE_STOCK,'SPTURIS'));
        $manager->persist($this->makeAsset('ALPA3',Asset::TYPE_STOCK,'ALPARGATAS'));
        $manager->persist($this->makeAsset('ALPA4',Asset::TYPE_STOCK,'ALPARGATAS'));
        $manager->persist($this->makeAsset('ALPK3',Asset::TYPE_STOCK,'ESTAPAR'));
        $manager->persist($this->makeAsset('ALSC3',Asset::TYPE_STOCK,'ALIANSCE'));
        $manager->persist($this->makeAsset('ALSO3',Asset::TYPE_STOCK,'ALIANSCSONAE'));
        $manager->persist($this->makeAsset('ALUP11',Asset::TYPE_STOCK,'ALUPAR'));
        $manager->persist($this->makeAsset('ALUP3',Asset::TYPE_STOCK,'ALUPAR'));
        $manager->persist($this->makeAsset('ALUP4',Asset::TYPE_STOCK,'ALUPAR'));
        $manager->persist($this->makeAsset('AMAR3',Asset::TYPE_STOCK,'LOJAS MARISA'));
        $manager->persist($this->makeAsset('AMBP3',Asset::TYPE_STOCK,'AMBIPAR'));
        $manager->persist($this->makeAsset('ANIM3',Asset::TYPE_STOCK,'ANIMA'));
        $manager->persist($this->makeAsset('APER3',Asset::TYPE_STOCK,'ALPER S.A.'));
        $manager->persist($this->makeAsset('APTI3',Asset::TYPE_STOCK,'ALIPERTI'));
        $manager->persist($this->makeAsset('APTI4',Asset::TYPE_STOCK,'ALIPERTI'));
        $manager->persist($this->makeAsset('ARZZ3',Asset::TYPE_STOCK,'AREZZO CO'));
        $manager->persist($this->makeAsset('ATOM3',Asset::TYPE_STOCK,'ATOMPAR'));
        $manager->persist($this->makeAsset('AURA33',Asset::TYPE_STOCK,'AURA 360'));
        $manager->persist($this->makeAsset('AVLL3',Asset::TYPE_STOCK,'ALPHAVILLE'));
        $manager->persist($this->makeAsset('AZEV3',Asset::TYPE_STOCK,'AZEVEDO'));
        $manager->persist($this->makeAsset('AZEV4',Asset::TYPE_STOCK,'AZEVEDO'));
        $manager->persist($this->makeAsset('AZUL4',Asset::TYPE_STOCK,'AZUL'));
        $manager->persist($this->makeAsset('B3SA3',Asset::TYPE_STOCK,'B3'));
        $manager->persist($this->makeAsset('BAHI3',Asset::TYPE_STOCK,'BAHEMA'));
        $manager->persist($this->makeAsset('BALM3',Asset::TYPE_STOCK,'BAUMER'));
        $manager->persist($this->makeAsset('BALM4',Asset::TYPE_STOCK,'BAUMER'));
        $manager->persist($this->makeAsset('BAUH3',Asset::TYPE_STOCK,'EXCELSIOR'));
        $manager->persist($this->makeAsset('BAUH4',Asset::TYPE_STOCK,'EXCELSIOR'));
        $manager->persist($this->makeAsset('BAZA3',Asset::TYPE_STOCK,'AMAZONIA'));
        $manager->persist($this->makeAsset('BBAS3',Asset::TYPE_STOCK,'BRASIL'));
        $manager->persist($this->makeAsset('BBDC3',Asset::TYPE_STOCK,'BRADESCO'));
        $manager->persist($this->makeAsset('BBDC4',Asset::TYPE_STOCK,'BRADESCO'));
        $manager->persist($this->makeAsset('BBML3',Asset::TYPE_STOCK,'BBMLOGISTICA'));
        $manager->persist($this->makeAsset('BBRK3',Asset::TYPE_STOCK,'BR BROKERS'));
        $manager->persist($this->makeAsset('BBSE3',Asset::TYPE_STOCK,'BBSEGURIDADE'));
        $manager->persist($this->makeAsset('BDLL3',Asset::TYPE_STOCK,'BARDELLA'));
        $manager->persist($this->makeAsset('BDLL4',Asset::TYPE_STOCK,'BARDELLA'));
        $manager->persist($this->makeAsset('BEEF3',Asset::TYPE_STOCK,'MINERVA'));
        $manager->persist($this->makeAsset('BEES3',Asset::TYPE_STOCK,'BANESTES'));
        $manager->persist($this->makeAsset('BEES4',Asset::TYPE_STOCK,'BANESTES'));
        $manager->persist($this->makeAsset('BGIP3',Asset::TYPE_STOCK,'BANESE'));
        $manager->persist($this->makeAsset('BGIP4',Asset::TYPE_STOCK,'BANESE'));
        $manager->persist($this->makeAsset('BIDI11',Asset::TYPE_STOCK,'BANCO INTER'));
        $manager->persist($this->makeAsset('BIDI3',Asset::TYPE_STOCK,'BANCO INTER'));
        $manager->persist($this->makeAsset('BIDI4',Asset::TYPE_STOCK,'BANCO INTER'));
        $manager->persist($this->makeAsset('BIOM3',Asset::TYPE_STOCK,'BIOMM'));
        $manager->persist($this->makeAsset('BKBR3',Asset::TYPE_STOCK,'BK BRASIL'));
        $manager->persist($this->makeAsset('BMEB3',Asset::TYPE_STOCK,'MERC BRASIL'));
        $manager->persist($this->makeAsset('BMEB4',Asset::TYPE_STOCK,'MERC BRASIL'));
        $manager->persist($this->makeAsset('BMGB4',Asset::TYPE_STOCK,'BANCO BMG'));
        $manager->persist($this->makeAsset('BMIN3',Asset::TYPE_STOCK,'MERC INVEST'));
        $manager->persist($this->makeAsset('BMIN4',Asset::TYPE_STOCK,'MERC INVEST'));
        $manager->persist($this->makeAsset('BMKS3',Asset::TYPE_STOCK,'BIC MONARK'));
        $manager->persist($this->makeAsset('BNBR3',Asset::TYPE_STOCK,'NORD BRASIL'));
        $manager->persist($this->makeAsset('BOAS3',Asset::TYPE_STOCK,'BOA VISTA'));
        $manager->persist($this->makeAsset('BOBR3',Asset::TYPE_STOCK,'BOMBRIL'));
        $manager->persist($this->makeAsset('BOBR4',Asset::TYPE_STOCK,'BOMBRIL'));
        $manager->persist($this->makeAsset('BPAC11',Asset::TYPE_STOCK,'BTGP BANCO'));
        $manager->persist($this->makeAsset('BPAC3',Asset::TYPE_STOCK,'BTGP BANCO'));
        $manager->persist($this->makeAsset('BPAC5',Asset::TYPE_STOCK,'BTGP BANCO'));
        $manager->persist($this->makeAsset('BPAN4',Asset::TYPE_STOCK,'BANCO PAN'));
        $manager->persist($this->makeAsset('BPAR3',Asset::TYPE_STOCK,'BANPARA'));
        $manager->persist($this->makeAsset('BPHA3',Asset::TYPE_STOCK,'BR PHARMA'));
        $manager->persist($this->makeAsset('BRAP3',Asset::TYPE_STOCK,'BRADESPAR'));
        $manager->persist($this->makeAsset('BRAP4',Asset::TYPE_STOCK,'BRADESPAR'));
        $manager->persist($this->makeAsset('BRDT3',Asset::TYPE_STOCK,'PETROBRAS BR'));
        $manager->persist($this->makeAsset('BRFS3',Asset::TYPE_STOCK,'BRF SA'));
        $manager->persist($this->makeAsset('BRGE11',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE12',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE3',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE5',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE6',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE7',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRGE8',Asset::TYPE_STOCK,'ALFA CONSORC'));
        $manager->persist($this->makeAsset('BRIV3',Asset::TYPE_STOCK,'ALFA INVEST'));
        $manager->persist($this->makeAsset('BRIV4',Asset::TYPE_STOCK,'ALFA INVEST'));
        $manager->persist($this->makeAsset('BRKM3',Asset::TYPE_STOCK,'BRASKEM'));
        $manager->persist($this->makeAsset('BRKM5',Asset::TYPE_STOCK,'BRASKEM'));
        $manager->persist($this->makeAsset('BRKM6',Asset::TYPE_STOCK,'BRASKEM'));
        $manager->persist($this->makeAsset('BRML3',Asset::TYPE_STOCK,'BR MALLS PAR'));
        $manager->persist($this->makeAsset('BRPR3',Asset::TYPE_STOCK,'BR PROPERT'));
        $manager->persist($this->makeAsset('BRQB3',Asset::TYPE_STOCK,'BRQ'));
        $manager->persist($this->makeAsset('BRSR3',Asset::TYPE_STOCK,'BANRISUL'));
        $manager->persist($this->makeAsset('BRSR5',Asset::TYPE_STOCK,'BANRISUL'));
        $manager->persist($this->makeAsset('BRSR6',Asset::TYPE_STOCK,'BANRISUL'));
        $manager->persist($this->makeAsset('BSEV3',Asset::TYPE_STOCK,'BIOSEV'));
        $manager->persist($this->makeAsset('BSLI3',Asset::TYPE_STOCK,'BRB BANCO'));
        $manager->persist($this->makeAsset('BSLI4',Asset::TYPE_STOCK,'BRB BANCO'));
        $manager->persist($this->makeAsset('BTOW3',Asset::TYPE_STOCK,'B2W DIGITAL'));
        $manager->persist($this->makeAsset('BTTL3',Asset::TYPE_STOCK,'BATTISTELLA'));
        $manager->persist($this->makeAsset('CALI3',Asset::TYPE_STOCK,'CONST A LIND'));
        $manager->persist($this->makeAsset('CALI4',Asset::TYPE_STOCK,'CONST A LIND'));
        $manager->persist($this->makeAsset('CAMB3',Asset::TYPE_STOCK,'CAMBUCI'));
        $manager->persist($this->makeAsset('CAML3',Asset::TYPE_STOCK,'CAMIL'));
        $manager->persist($this->makeAsset('CARD3',Asset::TYPE_STOCK,'CSU CARDSYST'));
        $manager->persist($this->makeAsset('CASH3',Asset::TYPE_STOCK,'MELIUZ'));
        $manager->persist($this->makeAsset('CASN3',Asset::TYPE_STOCK,'CASAN'));
        $manager->persist($this->makeAsset('CASN4',Asset::TYPE_STOCK,'CASAN'));
        $manager->persist($this->makeAsset('CATA3',Asset::TYPE_STOCK,'IND CATAGUAS'));
        $manager->persist($this->makeAsset('CATA4',Asset::TYPE_STOCK,'IND CATAGUAS'));
        $manager->persist($this->makeAsset('CBEE3',Asset::TYPE_STOCK,'AMPLA ENERG'));
        $manager->persist($this->makeAsset('CCPR3',Asset::TYPE_STOCK,'CYRE COM-CCP'));
        $manager->persist($this->makeAsset('CCRO3',Asset::TYPE_STOCK,'CCR SA'));
        $manager->persist($this->makeAsset('CCXC3',Asset::TYPE_STOCK,'CCX CARVAO'));
        $manager->persist($this->makeAsset('CEAB3',Asset::TYPE_STOCK,'CEA MODAS'));
        $manager->persist($this->makeAsset('CEBR3',Asset::TYPE_STOCK,'CEB'));
        $manager->persist($this->makeAsset('CEBR5',Asset::TYPE_STOCK,'CEB'));
        $manager->persist($this->makeAsset('CEBR6',Asset::TYPE_STOCK,'CEB'));
        $manager->persist($this->makeAsset('CEDO3',Asset::TYPE_STOCK,'CEDRO'));
        $manager->persist($this->makeAsset('CEDO4',Asset::TYPE_STOCK,'CEDRO'));
        $manager->persist($this->makeAsset('CEEB3',Asset::TYPE_STOCK,'COELBA'));
        $manager->persist($this->makeAsset('CEEB5',Asset::TYPE_STOCK,'COELBA'));
        $manager->persist($this->makeAsset('CEEB6',Asset::TYPE_STOCK,'COELBA'));
        $manager->persist($this->makeAsset('CEED3',Asset::TYPE_STOCK,'CEEE-D'));
        $manager->persist($this->makeAsset('CEED4',Asset::TYPE_STOCK,'CEEE-D'));
        $manager->persist($this->makeAsset('CEGR3',Asset::TYPE_STOCK,'CEG'));
        $manager->persist($this->makeAsset('CEPE3',Asset::TYPE_STOCK,'CELPE'));
        $manager->persist($this->makeAsset('CEPE5',Asset::TYPE_STOCK,'CELPE'));
        $manager->persist($this->makeAsset('CEPE6',Asset::TYPE_STOCK,'CELPE'));
        $manager->persist($this->makeAsset('CESP3',Asset::TYPE_STOCK,'CESP'));
        $manager->persist($this->makeAsset('CESP5',Asset::TYPE_STOCK,'CESP'));
        $manager->persist($this->makeAsset('CESP6',Asset::TYPE_STOCK,'CESP'));
        $manager->persist($this->makeAsset('CGAS3',Asset::TYPE_STOCK,'COMGAS'));
        $manager->persist($this->makeAsset('CGAS5',Asset::TYPE_STOCK,'COMGAS'));
        $manager->persist($this->makeAsset('CGRA3',Asset::TYPE_STOCK,'GRAZZIOTIN'));
        $manager->persist($this->makeAsset('CGRA4',Asset::TYPE_STOCK,'GRAZZIOTIN'));
        $manager->persist($this->makeAsset('CIEL3',Asset::TYPE_STOCK,'CIELO'));
        $manager->persist($this->makeAsset('CLSC3',Asset::TYPE_STOCK,'CELESC'));
        $manager->persist($this->makeAsset('CLSC4',Asset::TYPE_STOCK,'CELESC'));
        $manager->persist($this->makeAsset('CMIG3',Asset::TYPE_STOCK,'CEMIG'));
        $manager->persist($this->makeAsset('CMIG4',Asset::TYPE_STOCK,'CEMIG'));
        $manager->persist($this->makeAsset('CMSA3',Asset::TYPE_STOCK,'CIMS'));
        $manager->persist($this->makeAsset('CMSA4',Asset::TYPE_STOCK,'CIMS'));
        $manager->persist($this->makeAsset('CNSY3',Asset::TYPE_STOCK,'CINESYSTEM'));
        $manager->persist($this->makeAsset('CNTO3',Asset::TYPE_STOCK,'CENTAURO'));
        $manager->persist($this->makeAsset('COCE3',Asset::TYPE_STOCK,'COELCE'));
        $manager->persist($this->makeAsset('COCE5',Asset::TYPE_STOCK,'COELCE'));
        $manager->persist($this->makeAsset('COCE6',Asset::TYPE_STOCK,'COELCE'));
        $manager->persist($this->makeAsset('COGN3',Asset::TYPE_STOCK,'COGNA ON'));
        $manager->persist($this->makeAsset('CORR3',Asset::TYPE_STOCK,'COR RIBEIRO'));
        $manager->persist($this->makeAsset('CORR4',Asset::TYPE_STOCK,'COR RIBEIRO'));
        $manager->persist($this->makeAsset('CPFE3',Asset::TYPE_STOCK,'CPFL ENERGIA'));
        $manager->persist($this->makeAsset('CPLE3',Asset::TYPE_STOCK,'COPEL'));
        $manager->persist($this->makeAsset('CPLE5',Asset::TYPE_STOCK,'COPEL'));
        $manager->persist($this->makeAsset('CPLE6',Asset::TYPE_STOCK,'COPEL'));
        $manager->persist($this->makeAsset('CRDE3',Asset::TYPE_STOCK,'CR2'));
        $manager->persist($this->makeAsset('CRFB3',Asset::TYPE_STOCK,'CARREFOUR BR'));
        $manager->persist($this->makeAsset('CRIV3',Asset::TYPE_STOCK,'ALFA FINANC'));
        $manager->persist($this->makeAsset('CRIV4',Asset::TYPE_STOCK,'ALFA FINANC'));
        $manager->persist($this->makeAsset('CRPG3',Asset::TYPE_STOCK,'CRISTAL'));
        $manager->persist($this->makeAsset('CRPG5',Asset::TYPE_STOCK,'CRISTAL'));
        $manager->persist($this->makeAsset('CRPG6',Asset::TYPE_STOCK,'CRISTAL'));
        $manager->persist($this->makeAsset('CSAB3',Asset::TYPE_STOCK,'SEG AL BAHIA'));
        $manager->persist($this->makeAsset('CSAB4',Asset::TYPE_STOCK,'SEG AL BAHIA'));
        $manager->persist($this->makeAsset('CSAN3',Asset::TYPE_STOCK,'COSAN'));
        $manager->persist($this->makeAsset('CSMG3',Asset::TYPE_STOCK,'COPASA'));
        $manager->persist($this->makeAsset('CSNA3',Asset::TYPE_STOCK,'SID NACIONAL'));
        $manager->persist($this->makeAsset('CSRN3',Asset::TYPE_STOCK,'COSERN'));
        $manager->persist($this->makeAsset('CSRN5',Asset::TYPE_STOCK,'COSERN'));
        $manager->persist($this->makeAsset('CSRN6',Asset::TYPE_STOCK,'COSERN'));
        $manager->persist($this->makeAsset('CTCA3',Asset::TYPE_STOCK,'CTC S.A.'));
        $manager->persist($this->makeAsset('CTKA3',Asset::TYPE_STOCK,'KARSTEN'));
        $manager->persist($this->makeAsset('CTKA4',Asset::TYPE_STOCK,'KARSTEN'));
        $manager->persist($this->makeAsset('CTNM3',Asset::TYPE_STOCK,'COTEMINAS'));
        $manager->persist($this->makeAsset('CTNM4',Asset::TYPE_STOCK,'COTEMINAS'));
        $manager->persist($this->makeAsset('CTSA3',Asset::TYPE_STOCK,'SANTANENSE'));
        $manager->persist($this->makeAsset('CTSA4',Asset::TYPE_STOCK,'SANTANENSE'));
        $manager->persist($this->makeAsset('CTSA8',Asset::TYPE_STOCK,'SANTANENSE'));
        $manager->persist($this->makeAsset('CURY3',Asset::TYPE_STOCK,'CURY S/A'));
        $manager->persist($this->makeAsset('CVCB3',Asset::TYPE_STOCK,'CVC BRASIL'));
        $manager->persist($this->makeAsset('CYRE3',Asset::TYPE_STOCK,'CYRELA REALT'));
        $manager->persist($this->makeAsset('DASA3',Asset::TYPE_STOCK,'DASA'));
        $manager->persist($this->makeAsset('DIRR3',Asset::TYPE_STOCK,'DIRECIONAL'));
        $manager->persist($this->makeAsset('DMMO3',Asset::TYPE_STOCK,'DOMMO'));
        $manager->persist($this->makeAsset('DMVF3',Asset::TYPE_STOCK,'D1000VFARMA'));
        $manager->persist($this->makeAsset('DOHL3',Asset::TYPE_STOCK,'DOHLER'));
        $manager->persist($this->makeAsset('DOHL4',Asset::TYPE_STOCK,'DOHLER'));
        $manager->persist($this->makeAsset('DTCY3',Asset::TYPE_STOCK,'DTCOM-DIRECT'));
        $manager->persist($this->makeAsset('DTCY4',Asset::TYPE_STOCK,'DTCOM-DIRECT'));
        $manager->persist($this->makeAsset('DTEX3',Asset::TYPE_STOCK,'DURATEX'));
        $manager->persist($this->makeAsset('EALT3',Asset::TYPE_STOCK,'ACO ALTONA'));
        $manager->persist($this->makeAsset('EALT4',Asset::TYPE_STOCK,'ACO ALTONA'));
        $manager->persist($this->makeAsset('ECOR3',Asset::TYPE_STOCK,'ECORODOVIAS'));
        $manager->persist($this->makeAsset('ECPR3',Asset::TYPE_STOCK,'ENCORPAR'));
        $manager->persist($this->makeAsset('ECPR4',Asset::TYPE_STOCK,'ENCORPAR'));
        $manager->persist($this->makeAsset('EEEL3',Asset::TYPE_STOCK,'CEEE-GT'));
        $manager->persist($this->makeAsset('EEEL4',Asset::TYPE_STOCK,'CEEE-GT'));
        $manager->persist($this->makeAsset('EGIE3',Asset::TYPE_STOCK,'ENGIE BRASIL'));
        $manager->persist($this->makeAsset('EKTR3',Asset::TYPE_STOCK,'ELEKTRO'));
        $manager->persist($this->makeAsset('EKTR4',Asset::TYPE_STOCK,'ELEKTRO'));
        $manager->persist($this->makeAsset('ELEK3',Asset::TYPE_STOCK,'ELEKEIROZ'));
        $manager->persist($this->makeAsset('ELEK4',Asset::TYPE_STOCK,'ELEKEIROZ'));
        $manager->persist($this->makeAsset('ELET3',Asset::TYPE_STOCK,'ELETROBRAS'));
        $manager->persist($this->makeAsset('ELET5',Asset::TYPE_STOCK,'ELETROBRAS'));
        $manager->persist($this->makeAsset('ELET6',Asset::TYPE_STOCK,'ELETROBRAS'));
        $manager->persist($this->makeAsset('EMAE3',Asset::TYPE_STOCK,'EMAE'));
        $manager->persist($this->makeAsset('EMAE4',Asset::TYPE_STOCK,'EMAE'));
        $manager->persist($this->makeAsset('EMBR3',Asset::TYPE_STOCK,'EMBRAER'));
        $manager->persist($this->makeAsset('ENAT3',Asset::TYPE_STOCK,'ENAUTA PART'));
        $manager->persist($this->makeAsset('ENBR3',Asset::TYPE_STOCK,'ENERGIAS BR'));
        $manager->persist($this->makeAsset('ENEV3',Asset::TYPE_STOCK,'ENEVA'));
        $manager->persist($this->makeAsset('ENGI11',Asset::TYPE_STOCK,'ENERGISA'));
        $manager->persist($this->makeAsset('ENGI3',Asset::TYPE_STOCK,'ENERGISA'));
        $manager->persist($this->makeAsset('ENGI4',Asset::TYPE_STOCK,'ENERGISA'));
        $manager->persist($this->makeAsset('ENJU3',Asset::TYPE_STOCK,'ENJOEI'));
        $manager->persist($this->makeAsset('ENMT3',Asset::TYPE_STOCK,'ENERGISA MT'));
        $manager->persist($this->makeAsset('ENMT4',Asset::TYPE_STOCK,'ENERGISA MT'));
        $manager->persist($this->makeAsset('EQPA3',Asset::TYPE_STOCK,'EQTL PARA'));
        $manager->persist($this->makeAsset('EQPA5',Asset::TYPE_STOCK,'EQTL PARA'));
        $manager->persist($this->makeAsset('EQPA6',Asset::TYPE_STOCK,'EQTL PARA'));
        $manager->persist($this->makeAsset('EQPA7',Asset::TYPE_STOCK,'EQTL PARA'));
        $manager->persist($this->makeAsset('EQTL3',Asset::TYPE_STOCK,'EQUATORIAL'));
        $manager->persist($this->makeAsset('ESTR3',Asset::TYPE_STOCK,'ESTRELA'));
        $manager->persist($this->makeAsset('ESTR4',Asset::TYPE_STOCK,'ESTRELA'));
        $manager->persist($this->makeAsset('ETER3',Asset::TYPE_STOCK,'ETERNIT'));
        $manager->persist($this->makeAsset('EUCA3',Asset::TYPE_STOCK,'EUCATEX'));
        $manager->persist($this->makeAsset('EUCA4',Asset::TYPE_STOCK,'EUCATEX'));
        $manager->persist($this->makeAsset('EVEN3',Asset::TYPE_STOCK,'EVEN'));
        $manager->persist($this->makeAsset('EZTC3',Asset::TYPE_STOCK,'EZTEC'));
        $manager->persist($this->makeAsset('FESA3',Asset::TYPE_STOCK,'FERBASA'));
        $manager->persist($this->makeAsset('FESA4',Asset::TYPE_STOCK,'FERBASA'));
        $manager->persist($this->makeAsset('FHER3',Asset::TYPE_STOCK,'FER HERINGER'));
        $manager->persist($this->makeAsset('FIGE3',Asset::TYPE_STOCK,'INVEST BEMGE'));
        $manager->persist($this->makeAsset('FIGE4',Asset::TYPE_STOCK,'INVEST BEMGE'));
        $manager->persist($this->makeAsset('FLEX3',Asset::TYPE_STOCK,'FLEX S/A'));
        $manager->persist($this->makeAsset('FLRY3',Asset::TYPE_STOCK,'FLEURY'));
        $manager->persist($this->makeAsset('FNCN3',Asset::TYPE_STOCK,'FINANSINOS'));
        $manager->persist($this->makeAsset('FRAS3',Asset::TYPE_STOCK,'FRAS-LE'));
        $manager->persist($this->makeAsset('FRIO3',Asset::TYPE_STOCK,'METALFRIO'));
        $manager->persist($this->makeAsset('FRTA3',Asset::TYPE_STOCK,'POMIFRUTAS'));
        $manager->persist($this->makeAsset('GEPA3',Asset::TYPE_STOCK,'GER PARANAP'));
        $manager->persist($this->makeAsset('GEPA4',Asset::TYPE_STOCK,'GER PARANAP'));
        $manager->persist($this->makeAsset('GFSA3',Asset::TYPE_STOCK,'GAFISA'));
        $manager->persist($this->makeAsset('GGBR3',Asset::TYPE_STOCK,'GERDAU'));
        $manager->persist($this->makeAsset('GGBR4',Asset::TYPE_STOCK,'GERDAU'));
        $manager->persist($this->makeAsset('GMAT3',Asset::TYPE_STOCK,'GRUPO MATEUS'));
        $manager->persist($this->makeAsset('GNDI3',Asset::TYPE_STOCK,'INTERMEDICA'));
        $manager->persist($this->makeAsset('GOAU3',Asset::TYPE_STOCK,'GERDAU MET'));
        $manager->persist($this->makeAsset('GOAU4',Asset::TYPE_STOCK,'GERDAU MET'));
        $manager->persist($this->makeAsset('GOLL4',Asset::TYPE_STOCK,'GOL'));
        $manager->persist($this->makeAsset('GPAR3',Asset::TYPE_STOCK,'CELGPAR'));
        $manager->persist($this->makeAsset('GPCP3',Asset::TYPE_STOCK,'GPC PART'));
        $manager->persist($this->makeAsset('GPCP4',Asset::TYPE_STOCK,'GPC PART'));
        $manager->persist($this->makeAsset('GPIV33',Asset::TYPE_STOCK,'GP INVEST'));
        $manager->persist($this->makeAsset('GRND3',Asset::TYPE_STOCK,'GRENDENE'));
        $manager->persist($this->makeAsset('GSHP3',Asset::TYPE_STOCK,'GENERALSHOPP'));
        $manager->persist($this->makeAsset('GUAR3',Asset::TYPE_STOCK,'GUARARAPES'));
        $manager->persist($this->makeAsset('HAGA3',Asset::TYPE_STOCK,'HAGA S/A'));
        $manager->persist($this->makeAsset('HAGA4',Asset::TYPE_STOCK,'HAGA S/A'));
        $manager->persist($this->makeAsset('HAPV3',Asset::TYPE_STOCK,'HAPVIDA'));
        $manager->persist($this->makeAsset('HBOR3',Asset::TYPE_STOCK,'HELBOR'));
        $manager->persist($this->makeAsset('HBSA3',Asset::TYPE_STOCK,'HIDROVIAS'));
        $manager->persist($this->makeAsset('HBTS3',Asset::TYPE_STOCK,'HABITASUL'));
        $manager->persist($this->makeAsset('HBTS5',Asset::TYPE_STOCK,'HABITASUL'));
        $manager->persist($this->makeAsset('HBTS6',Asset::TYPE_STOCK,'HABITASUL'));
        $manager->persist($this->makeAsset('HCBR3',Asset::TYPE_STOCK,'BR HOME'));
        $manager->persist($this->makeAsset('HETA3',Asset::TYPE_STOCK,'HERCULES'));
        $manager->persist($this->makeAsset('HETA4',Asset::TYPE_STOCK,'HERCULES'));
        $manager->persist($this->makeAsset('HGTX3',Asset::TYPE_STOCK,'CIA HERING'));
        $manager->persist($this->makeAsset('HOOT3',Asset::TYPE_STOCK,'HOTEIS OTHON'));
        $manager->persist($this->makeAsset('HOOT4',Asset::TYPE_STOCK,'HOTEIS OTHON'));
        $manager->persist($this->makeAsset('HYPE3',Asset::TYPE_STOCK,'HYPERA'));
        $manager->persist($this->makeAsset('IGBR3',Asset::TYPE_STOCK,'IGB S/A'));
        $manager->persist($this->makeAsset('IGSN3',Asset::TYPE_STOCK,'IGUA SA'));
        $manager->persist($this->makeAsset('IGTA3',Asset::TYPE_STOCK,'IGUATEMI'));
        $manager->persist($this->makeAsset('INEP3',Asset::TYPE_STOCK,'INEPAR'));
        $manager->persist($this->makeAsset('INEP4',Asset::TYPE_STOCK,'INEPAR'));
        $manager->persist($this->makeAsset('INNT3',Asset::TYPE_STOCK,'INTER SA'));
        $manager->persist($this->makeAsset('IRBR3',Asset::TYPE_STOCK,'IRBBRASIL RE'));
        $manager->persist($this->makeAsset('ITEC3',Asset::TYPE_STOCK,'ITAUTEC'));
        $manager->persist($this->makeAsset('ITSA3',Asset::TYPE_STOCK,'ITAUSA'));
        $manager->persist($this->makeAsset('ITSA4',Asset::TYPE_STOCK,'ITAUSA'));
        $manager->persist($this->makeAsset('ITUB3',Asset::TYPE_STOCK,'ITAUUNIBANCO'));
        $manager->persist($this->makeAsset('ITUB4',Asset::TYPE_STOCK,'ITAUUNIBANCO'));
        $manager->persist($this->makeAsset('JBDU3',Asset::TYPE_STOCK,'J B DUARTE'));
        $manager->persist($this->makeAsset('JBDU4',Asset::TYPE_STOCK,'J B DUARTE'));
        $manager->persist($this->makeAsset('JBSS3',Asset::TYPE_STOCK,'JBS'));
        $manager->persist($this->makeAsset('JFEN3',Asset::TYPE_STOCK,'JOAO FORTES'));
        $manager->persist($this->makeAsset('JHSF3',Asset::TYPE_STOCK,'JHSF PART'));
        $manager->persist($this->makeAsset('JOPA3',Asset::TYPE_STOCK,'JOSAPAR'));
        $manager->persist($this->makeAsset('JOPA4',Asset::TYPE_STOCK,'JOSAPAR'));
        $manager->persist($this->makeAsset('JPSA3',Asset::TYPE_STOCK,'JEREISSATI'));
        $manager->persist($this->makeAsset('KEPL3',Asset::TYPE_STOCK,'KEPLER WEBER'));
        $manager->persist($this->makeAsset('KLBN11',Asset::TYPE_STOCK,'KLABIN S/A'));
        $manager->persist($this->makeAsset('KLBN3',Asset::TYPE_STOCK,'KLABIN S/A'));
        $manager->persist($this->makeAsset('KLBN4',Asset::TYPE_STOCK,'KLABIN S/A'));
        $manager->persist($this->makeAsset('LAME3',Asset::TYPE_STOCK,'LOJAS AMERIC'));
        $manager->persist($this->makeAsset('LAME4',Asset::TYPE_STOCK,'LOJAS AMERIC'));
        $manager->persist($this->makeAsset('LAVV3',Asset::TYPE_STOCK,'LAVVI'));
        $manager->persist($this->makeAsset('LCAM3',Asset::TYPE_STOCK,'LOCAMERICA'));
        $manager->persist($this->makeAsset('LEVE3',Asset::TYPE_STOCK,'METAL LEVE'));
        $manager->persist($this->makeAsset('LHER3',Asset::TYPE_STOCK,'LOJAS HERING'));
        $manager->persist($this->makeAsset('LHER4',Asset::TYPE_STOCK,'LOJAS HERING'));
        $manager->persist($this->makeAsset('LIGT3',Asset::TYPE_STOCK,'LIGHT S/A'));
        $manager->persist($this->makeAsset('LINX3',Asset::TYPE_STOCK,'LINX'));
        $manager->persist($this->makeAsset('LIPR3',Asset::TYPE_STOCK,'ELETROPAR'));
        $manager->persist($this->makeAsset('LJQQ3',Asset::TYPE_STOCK,'QUERO-QUERO'));
        $manager->persist($this->makeAsset('LMED3',Asset::TYPE_STOCK,'LIFEMED'));
        $manager->persist($this->makeAsset('LOGG3',Asset::TYPE_STOCK,'LOG COM PROP'));
        $manager->persist($this->makeAsset('LOGN3',Asset::TYPE_STOCK,'LOG-IN'));
        $manager->persist($this->makeAsset('LPSB3',Asset::TYPE_STOCK,'LOPES BRASIL'));
        $manager->persist($this->makeAsset('LREN3',Asset::TYPE_STOCK,'LOJAS RENNER'));
        $manager->persist($this->makeAsset('LUPA3',Asset::TYPE_STOCK,'LUPATECH'));
        $manager->persist($this->makeAsset('LUXM3',Asset::TYPE_STOCK,'TREVISA'));
        $manager->persist($this->makeAsset('LUXM4',Asset::TYPE_STOCK,'TREVISA'));
        $manager->persist($this->makeAsset('LWSA3',Asset::TYPE_STOCK,'LOCAWEB'));
        $manager->persist($this->makeAsset('MAPT3',Asset::TYPE_STOCK,'CEMEPE'));
        $manager->persist($this->makeAsset('MAPT4',Asset::TYPE_STOCK,'CEMEPE'));
        $manager->persist($this->makeAsset('MDIA3',Asset::TYPE_STOCK,'M.DIASBRANCO'));
        $manager->persist($this->makeAsset('MDNE3',Asset::TYPE_STOCK,'MOURA DUBEUX'));
        $manager->persist($this->makeAsset('MEAL3',Asset::TYPE_STOCK,'IMC S/A'));
        $manager->persist($this->makeAsset('MELK3',Asset::TYPE_STOCK,'MELNICK'));
        $manager->persist($this->makeAsset('MERC3',Asset::TYPE_STOCK,'MERC FINANC'));
        $manager->persist($this->makeAsset('MERC4',Asset::TYPE_STOCK,'MERC FINANC'));
        $manager->persist($this->makeAsset('MGEL3',Asset::TYPE_STOCK,'MANGELS INDL'));
        $manager->persist($this->makeAsset('MGEL4',Asset::TYPE_STOCK,'MANGELS INDL'));
        $manager->persist($this->makeAsset('MGLU3',Asset::TYPE_STOCK,'MAGAZ LUIZA'));
        $manager->persist($this->makeAsset('MILS3',Asset::TYPE_STOCK,'MILLS'));
        $manager->persist($this->makeAsset('MMAQ3',Asset::TYPE_STOCK,'MINASMAQUINA'));
        $manager->persist($this->makeAsset('MMAQ4',Asset::TYPE_STOCK,'MINASMAQUINA'));
        $manager->persist($this->makeAsset('MMXM3',Asset::TYPE_STOCK,'MMX MINER'));
        $manager->persist($this->makeAsset('MNDL3',Asset::TYPE_STOCK,'MUNDIAL'));
        $manager->persist($this->makeAsset('MNPR3',Asset::TYPE_STOCK,'MINUPAR'));
        $manager->persist($this->makeAsset('MOAR3',Asset::TYPE_STOCK,'MONT ARANHA'));
        $manager->persist($this->makeAsset('MOVI3',Asset::TYPE_STOCK,'MOVIDA'));
        $manager->persist($this->makeAsset('MPLU3',Asset::TYPE_STOCK,'MULTIPLUS'));
        $manager->persist($this->makeAsset('MRFG3',Asset::TYPE_STOCK,'MARFRIG'));
        $manager->persist($this->makeAsset('MRVE3',Asset::TYPE_STOCK,'MRV'));
        $manager->persist($this->makeAsset('MSPA3',Asset::TYPE_STOCK,'MELHOR SP'));
        $manager->persist($this->makeAsset('MSPA4',Asset::TYPE_STOCK,'MELHOR SP'));
        $manager->persist($this->makeAsset('MSRO3',Asset::TYPE_STOCK,'MAESTROLOC'));
        $manager->persist($this->makeAsset('MTIG3',Asset::TYPE_STOCK,'METAL IGUACU'));
        $manager->persist($this->makeAsset('MTIG4',Asset::TYPE_STOCK,'METAL IGUACU'));
        $manager->persist($this->makeAsset('MTRE3',Asset::TYPE_STOCK,'MITRE REALTY'));
        $manager->persist($this->makeAsset('MTSA3',Asset::TYPE_STOCK,'METISA'));
        $manager->persist($this->makeAsset('MTSA4',Asset::TYPE_STOCK,'METISA'));
        $manager->persist($this->makeAsset('MULT3',Asset::TYPE_STOCK,'MULTIPLAN'));
        $manager->persist($this->makeAsset('MWET3',Asset::TYPE_STOCK,'WETZEL S/A'));
        $manager->persist($this->makeAsset('MWET4',Asset::TYPE_STOCK,'WETZEL S/A'));
        $manager->persist($this->makeAsset('MYPK3',Asset::TYPE_STOCK,'IOCHP-MAXION'));
        $manager->persist($this->makeAsset('NAFG3',Asset::TYPE_STOCK,'NADIR FIGUEI'));
        $manager->persist($this->makeAsset('NAFG4',Asset::TYPE_STOCK,'NADIR FIGUEI'));
        $manager->persist($this->makeAsset('NEMO3',Asset::TYPE_STOCK,'SUZANO HOLD'));
        $manager->persist($this->makeAsset('NEMO5',Asset::TYPE_STOCK,'SUZANO HOLD'));
        $manager->persist($this->makeAsset('NEMO6',Asset::TYPE_STOCK,'SUZANO HOLD'));
        $manager->persist($this->makeAsset('NEOE3',Asset::TYPE_STOCK,'NEOENERGIA'));
        $manager->persist($this->makeAsset('NGRD3',Asset::TYPE_STOCK,'NEOGRID'));
        $manager->persist($this->makeAsset('NORD3',Asset::TYPE_STOCK,'NORDON MET'));
        $manager->persist($this->makeAsset('NRTQ3',Asset::TYPE_STOCK,'NORTCQUIMICA'));
        $manager->persist($this->makeAsset('NTCO3',Asset::TYPE_STOCK,'GRUPO NATURA'));
        $manager->persist($this->makeAsset('ODER3',Asset::TYPE_STOCK,'ODERICH'));
        $manager->persist($this->makeAsset('ODER4',Asset::TYPE_STOCK,'ODERICH'));
        $manager->persist($this->makeAsset('ODPV3',Asset::TYPE_STOCK,'ODONTOPREV'));
        $manager->persist($this->makeAsset('OFSA3',Asset::TYPE_STOCK,'OUROFINO S/A'));
        $manager->persist($this->makeAsset('OIBR3',Asset::TYPE_STOCK,'OI'));
        $manager->persist($this->makeAsset('OIBR4',Asset::TYPE_STOCK,'OI'));
        $manager->persist($this->makeAsset('OMGE3',Asset::TYPE_STOCK,'OMEGA GER'));
        $manager->persist($this->makeAsset('OSXB3',Asset::TYPE_STOCK,'OSX BRASIL'));
        $manager->persist($this->makeAsset('PACF3',Asset::TYPE_STOCK,'PACIFIC RDSL'));
        $manager->persist($this->makeAsset('PARD3',Asset::TYPE_STOCK,'IHPARDINI'));
        $manager->persist($this->makeAsset('PATI3',Asset::TYPE_STOCK,'PANATLANTICA'));
        $manager->persist($this->makeAsset('PATI4',Asset::TYPE_STOCK,'PANATLANTICA'));
        $manager->persist($this->makeAsset('PCAR3',Asset::TYPE_STOCK,'P.ACUCAR-CBD'));
        $manager->persist($this->makeAsset('PDGR3',Asset::TYPE_STOCK,'PDG REALT'));
        $manager->persist($this->makeAsset('PDTC3',Asset::TYPE_STOCK,'PADTEC'));
        $manager->persist($this->makeAsset('PEAB3',Asset::TYPE_STOCK,'PAR AL BAHIA'));
        $manager->persist($this->makeAsset('PEAB4',Asset::TYPE_STOCK,'PAR AL BAHIA'));
        $manager->persist($this->makeAsset('PETR3',Asset::TYPE_STOCK,'PETROBRAS'));
        $manager->persist($this->makeAsset('PETR4',Asset::TYPE_STOCK,'PETROBRAS'));
        $manager->persist($this->makeAsset('PETZ3',Asset::TYPE_STOCK,'PETZ'));
        $manager->persist($this->makeAsset('PFRM3',Asset::TYPE_STOCK,'PROFARMA'));
        $manager->persist($this->makeAsset('PGMN3',Asset::TYPE_STOCK,'PAGUE MENOS'));
        $manager->persist($this->makeAsset('PINE3',Asset::TYPE_STOCK,'PINE'));
        $manager->persist($this->makeAsset('PINE4',Asset::TYPE_STOCK,'PINE'));
        $manager->persist($this->makeAsset('PLAS3',Asset::TYPE_STOCK,'PLASCAR PART'));
        $manager->persist($this->makeAsset('PLPL3',Asset::TYPE_STOCK,'PLANOEPLANO'));
        $manager->persist($this->makeAsset('PMAM3',Asset::TYPE_STOCK,'PARANAPANEMA'));
        $manager->persist($this->makeAsset('PNVL3',Asset::TYPE_STOCK,'DIMED'));
        $manager->persist($this->makeAsset('PNVL4',Asset::TYPE_STOCK,'DIMED'));
        $manager->persist($this->makeAsset('POMO3',Asset::TYPE_STOCK,'MARCOPOLO'));
        $manager->persist($this->makeAsset('POMO4',Asset::TYPE_STOCK,'MARCOPOLO'));
        $manager->persist($this->makeAsset('POSI3',Asset::TYPE_STOCK,'POSITIVO TEC'));
        $manager->persist($this->makeAsset('PPAR3',Asset::TYPE_STOCK,'POLPAR'));
        $manager->persist($this->makeAsset('PPLA11',Asset::TYPE_STOCK,'PPLA'));
        $manager->persist($this->makeAsset('PRIO3',Asset::TYPE_STOCK,'PETRORIO'));
        $manager->persist($this->makeAsset('PRNR3',Asset::TYPE_STOCK,'PRINER'));
        $manager->persist($this->makeAsset('PSSA3',Asset::TYPE_STOCK,'PORTO SEGURO'));
        $manager->persist($this->makeAsset('PTBL3',Asset::TYPE_STOCK,'PORTOBELLO'));
        $manager->persist($this->makeAsset('PTCA11',Asset::TYPE_STOCK,'PRATICA'));
        $manager->persist($this->makeAsset('PTCA3',Asset::TYPE_STOCK,'PRATICA'));
        $manager->persist($this->makeAsset('PTNT3',Asset::TYPE_STOCK,'PETTENATI'));
        $manager->persist($this->makeAsset('PTNT4',Asset::TYPE_STOCK,'PETTENATI'));
        $manager->persist($this->makeAsset('QUAL3',Asset::TYPE_STOCK,'QUALICORP'));
        $manager->persist($this->makeAsset('QUSW3',Asset::TYPE_STOCK,'QUALITY SOFT'));
        $manager->persist($this->makeAsset('RADL3',Asset::TYPE_STOCK,'RAIADROGASIL'));
        $manager->persist($this->makeAsset('RAIL3',Asset::TYPE_STOCK,'RUMO S.A.'));
        $manager->persist($this->makeAsset('RANI3',Asset::TYPE_STOCK,'IRANI'));
        $manager->persist($this->makeAsset('RAPT3',Asset::TYPE_STOCK,'RANDON PART'));
        $manager->persist($this->makeAsset('RAPT4',Asset::TYPE_STOCK,'RANDON PART'));
        $manager->persist($this->makeAsset('RCSL3',Asset::TYPE_STOCK,'RECRUSUL'));
        $manager->persist($this->makeAsset('RCSL4',Asset::TYPE_STOCK,'RECRUSUL'));
        $manager->persist($this->makeAsset('RDNI3',Asset::TYPE_STOCK,'RNI'));
        $manager->persist($this->makeAsset('RDOR3',Asset::TYPE_STOCK,'REDE D OR'));
        $manager->persist($this->makeAsset('REDE3',Asset::TYPE_STOCK,'REDE ENERGIA'));
        $manager->persist($this->makeAsset('RENT3',Asset::TYPE_STOCK,'LOCALIZA'));
        $manager->persist($this->makeAsset('RLOG3',Asset::TYPE_STOCK,'COSAN LOG'));
        $manager->persist($this->makeAsset('RNEW11',Asset::TYPE_STOCK,'RENOVA'));
        $manager->persist($this->makeAsset('RNEW3',Asset::TYPE_STOCK,'RENOVA'));
        $manager->persist($this->makeAsset('RNEW4',Asset::TYPE_STOCK,'RENOVA'));
        $manager->persist($this->makeAsset('ROMI3',Asset::TYPE_STOCK,'INDS ROMI'));
        $manager->persist($this->makeAsset('RPAD3',Asset::TYPE_STOCK,'ALFA HOLDING'));
        $manager->persist($this->makeAsset('RPAD5',Asset::TYPE_STOCK,'ALFA HOLDING'));
        $manager->persist($this->makeAsset('RPAD6',Asset::TYPE_STOCK,'ALFA HOLDING'));
        $manager->persist($this->makeAsset('RPMG3',Asset::TYPE_STOCK,'PET MANGUINH'));
        $manager->persist($this->makeAsset('RRRP3',Asset::TYPE_STOCK,'3R PETROLEUM'));
        $manager->persist($this->makeAsset('RSID3',Asset::TYPE_STOCK,'ROSSI RESID'));
        $manager->persist($this->makeAsset('RSUL3',Asset::TYPE_STOCK,'RIOSULENSE'));
        $manager->persist($this->makeAsset('RSUL4',Asset::TYPE_STOCK,'RIOSULENSE'));
        $manager->persist($this->makeAsset('SANB11',Asset::TYPE_STOCK,'SANTANDER BR'));
        $manager->persist($this->makeAsset('SANB3',Asset::TYPE_STOCK,'SANTANDER BR'));
        $manager->persist($this->makeAsset('SANB4',Asset::TYPE_STOCK,'SANTANDER BR'));
        $manager->persist($this->makeAsset('SAPR11',Asset::TYPE_STOCK,'SANEPAR'));
        $manager->persist($this->makeAsset('SAPR3',Asset::TYPE_STOCK,'SANEPAR'));
        $manager->persist($this->makeAsset('SAPR4',Asset::TYPE_STOCK,'SANEPAR'));
        $manager->persist($this->makeAsset('SBSP3',Asset::TYPE_STOCK,'SABESP'));
        $manager->persist($this->makeAsset('SCAR3',Asset::TYPE_STOCK,'SAO CARLOS'));
        $manager->persist($this->makeAsset('SEDU3',Asset::TYPE_STOCK,'SOMOS EDUCA'));
        $manager->persist($this->makeAsset('SEER3',Asset::TYPE_STOCK,'SER EDUCA'));
        $manager->persist($this->makeAsset('SEQL3',Asset::TYPE_STOCK,'SEQUOIA LOG'));
        $manager->persist($this->makeAsset('SGPS3',Asset::TYPE_STOCK,'SPRINGS'));
        $manager->persist($this->makeAsset('SHOW3',Asset::TYPE_STOCK,'TIME FOR FUN'));
        $manager->persist($this->makeAsset('SHUL3',Asset::TYPE_STOCK,'SCHULZ'));
        $manager->persist($this->makeAsset('SHUL4',Asset::TYPE_STOCK,'SCHULZ'));
        $manager->persist($this->makeAsset('SIMH3',Asset::TYPE_STOCK,'SIMPAR'));
        $manager->persist($this->makeAsset('SLCE3',Asset::TYPE_STOCK,'SLC AGRICOLA'));
        $manager->persist($this->makeAsset('SLED3',Asset::TYPE_STOCK,'SARAIVA LIVR'));
        $manager->persist($this->makeAsset('SLED4',Asset::TYPE_STOCK,'SARAIVA LIVR'));
        $manager->persist($this->makeAsset('SMFT3',Asset::TYPE_STOCK,'SMART FIT'));
        $manager->persist($this->makeAsset('SMLS3',Asset::TYPE_STOCK,'SMILES'));
        $manager->persist($this->makeAsset('SMTO3',Asset::TYPE_STOCK,'SAO MARTINHO'));
        $manager->persist($this->makeAsset('SNSY3',Asset::TYPE_STOCK,'SANSUY'));
        $manager->persist($this->makeAsset('SNSY5',Asset::TYPE_STOCK,'SANSUY'));
        $manager->persist($this->makeAsset('SNSY6',Asset::TYPE_STOCK,'SANSUY'));
        $manager->persist($this->makeAsset('SOMA3',Asset::TYPE_STOCK,'GRUPO SOMA'));
        $manager->persist($this->makeAsset('SOND3',Asset::TYPE_STOCK,'SONDOTECNICA'));
        $manager->persist($this->makeAsset('SOND5',Asset::TYPE_STOCK,'SONDOTECNICA'));
        $manager->persist($this->makeAsset('SOND6',Asset::TYPE_STOCK,'SONDOTECNICA'));
        $manager->persist($this->makeAsset('SPRI3',Asset::TYPE_STOCK,'SPRINGER'));
        $manager->persist($this->makeAsset('SPRI5',Asset::TYPE_STOCK,'SPRINGER'));
        $manager->persist($this->makeAsset('SPRI6',Asset::TYPE_STOCK,'SPRINGER'));
        $manager->persist($this->makeAsset('SQIA3',Asset::TYPE_STOCK,'SINQIA'));
        $manager->persist($this->makeAsset('STBP3',Asset::TYPE_STOCK,'SANTOS BRP'));
        $manager->persist($this->makeAsset('STKF3',Asset::TYPE_STOCK,'STATKRAFT'));
        $manager->persist($this->makeAsset('STTR3',Asset::TYPE_STOCK,'STARA'));
        $manager->persist($this->makeAsset('SULA11',Asset::TYPE_STOCK,'SUL AMERICA'));
        $manager->persist($this->makeAsset('SULA3',Asset::TYPE_STOCK,'SUL AMERICA'));
        $manager->persist($this->makeAsset('SULA4',Asset::TYPE_STOCK,'SUL AMERICA'));
        $manager->persist($this->makeAsset('SUZB3',Asset::TYPE_STOCK,'SUZANO S.A.'));
        $manager->persist($this->makeAsset('TAEE11',Asset::TYPE_STOCK,'TAESA'));
        $manager->persist($this->makeAsset('TAEE3',Asset::TYPE_STOCK,'TAESA'));
        $manager->persist($this->makeAsset('TAEE4',Asset::TYPE_STOCK,'TAESA'));
        $manager->persist($this->makeAsset('TASA3',Asset::TYPE_STOCK,'TAURUS ARMAS'));
        $manager->persist($this->makeAsset('TASA4',Asset::TYPE_STOCK,'TAURUS ARMAS'));
        $manager->persist($this->makeAsset('TCNO3',Asset::TYPE_STOCK,'TECNOSOLO'));
        $manager->persist($this->makeAsset('TCNO4',Asset::TYPE_STOCK,'TECNOSOLO'));
        $manager->persist($this->makeAsset('TCSA3',Asset::TYPE_STOCK,'TECNISA'));
        $manager->persist($this->makeAsset('TECN3',Asset::TYPE_STOCK,'TECHNOS'));
        $manager->persist($this->makeAsset('TEKA3',Asset::TYPE_STOCK,'TEKA'));
        $manager->persist($this->makeAsset('TEKA4',Asset::TYPE_STOCK,'TEKA'));
        $manager->persist($this->makeAsset('TELB3',Asset::TYPE_STOCK,'TELEBRAS'));
        $manager->persist($this->makeAsset('TELB4',Asset::TYPE_STOCK,'TELEBRAS'));
        $manager->persist($this->makeAsset('TEND3',Asset::TYPE_STOCK,'TENDA'));
        $manager->persist($this->makeAsset('TESA3',Asset::TYPE_STOCK,'TERRA SANTA'));
        $manager->persist($this->makeAsset('TFCO4',Asset::TYPE_STOCK,'TRACK FIELD'));
        $manager->persist($this->makeAsset('TGMA3',Asset::TYPE_STOCK,'TEGMA'));
        $manager->persist($this->makeAsset('TIET11',Asset::TYPE_STOCK,'AES TIETE E'));
        $manager->persist($this->makeAsset('TIET3',Asset::TYPE_STOCK,'AES TIETE E'));
        $manager->persist($this->makeAsset('TIET4',Asset::TYPE_STOCK,'AES TIETE E'));
        $manager->persist($this->makeAsset('TIMS3',Asset::TYPE_STOCK,'TIM'));
        $manager->persist($this->makeAsset('TKNO3',Asset::TYPE_STOCK,'TEKNO'));
        $manager->persist($this->makeAsset('TKNO4',Asset::TYPE_STOCK,'TEKNO'));
        $manager->persist($this->makeAsset('TOTS3',Asset::TYPE_STOCK,'TOTVS'));
        $manager->persist($this->makeAsset('TOYB3',Asset::TYPE_STOCK,'TECTOY'));
        $manager->persist($this->makeAsset('TOYB4',Asset::TYPE_STOCK,'TECTOY'));
        $manager->persist($this->makeAsset('TPIS3',Asset::TYPE_STOCK,'TRIUNFO PART'));
        $manager->persist($this->makeAsset('TRIS3',Asset::TYPE_STOCK,'TRISUL'));
        $manager->persist($this->makeAsset('TRPL3',Asset::TYPE_STOCK,'TRAN PAULIST'));
        $manager->persist($this->makeAsset('TRPL4',Asset::TYPE_STOCK,'TRAN PAULIST'));
        $manager->persist($this->makeAsset('TRPN3',Asset::TYPE_STOCK,'TARPON INV'));
        $manager->persist($this->makeAsset('TUPY3',Asset::TYPE_STOCK,'TUPY'));
        $manager->persist($this->makeAsset('UCAS3',Asset::TYPE_STOCK,'UNICASA'));
        $manager->persist($this->makeAsset('UGPA3',Asset::TYPE_STOCK,'ULTRAPAR'));
        $manager->persist($this->makeAsset('UNIP3',Asset::TYPE_STOCK,'UNIPAR'));
        $manager->persist($this->makeAsset('UNIP5',Asset::TYPE_STOCK,'UNIPAR'));
        $manager->persist($this->makeAsset('UNIP6',Asset::TYPE_STOCK,'UNIPAR'));
        $manager->persist($this->makeAsset('USIM3',Asset::TYPE_STOCK,'USIMINAS'));
        $manager->persist($this->makeAsset('USIM5',Asset::TYPE_STOCK,'USIMINAS'));
        $manager->persist($this->makeAsset('USIM6',Asset::TYPE_STOCK,'USIMINAS'));
        $manager->persist($this->makeAsset('VALE3',Asset::TYPE_STOCK,'VALE'));
        $manager->persist($this->makeAsset('VIVA3',Asset::TYPE_STOCK,'VIVARA S.A.'));
        $manager->persist($this->makeAsset('VIVR3',Asset::TYPE_STOCK,'VIVER'));
        $manager->persist($this->makeAsset('VIVT3',Asset::TYPE_STOCK,'TELEF BRASIL'));
        $manager->persist($this->makeAsset('VLID3',Asset::TYPE_STOCK,'VALID'));
        $manager->persist($this->makeAsset('VSPT3',Asset::TYPE_STOCK,'FER C ATLANT'));
        $manager->persist($this->makeAsset('VSPT4',Asset::TYPE_STOCK,'FER C ATLANT'));
        $manager->persist($this->makeAsset('VULC3',Asset::TYPE_STOCK,'VULCABRAS'));
        $manager->persist($this->makeAsset('VVAR3',Asset::TYPE_STOCK,'VIAVAREJO'));
        $manager->persist($this->makeAsset('WEGE3',Asset::TYPE_STOCK,'WEG'));
        $manager->persist($this->makeAsset('WHRL3',Asset::TYPE_STOCK,'WHIRLPOOL'));
        $manager->persist($this->makeAsset('WHRL4',Asset::TYPE_STOCK,'WHIRLPOOL'));
        $manager->persist($this->makeAsset('WIZS3',Asset::TYPE_STOCK,'WIZ S.A.'));
        $manager->persist($this->makeAsset('WLMM3',Asset::TYPE_STOCK,'WLM IND COM'));
        $manager->persist($this->makeAsset('WLMM4',Asset::TYPE_STOCK,'WLM IND COM'));
        $manager->persist($this->makeAsset('WSON33',Asset::TYPE_STOCK,'WILSON SONS'));
        $manager->persist($this->makeAsset('YDUQ3',Asset::TYPE_STOCK,'YDUQS PART'));

        $manager->flush();
    }

    private function makeAsset(string $code, string $type, string $description): Asset
    {
        return (new Asset())
            ->setCode($code)
            ->setType($type)
            ->setDescription($description);
    }
}
